### ISSUE TITLE
Appending Modified page to Modified Page

### ISSUE THREAD

**Issue by jaspersorrio** [galkahana/HummusJS#101]
Hi Gal,

I need some help again.. Hehe

I am trying to append a modified page to another modified page. I wonder how i might do that?

Also, how do i access [writeText](https://github.com/galkahana/HummusJS/wiki/Show-text) and [drawRectangle](https://github.com/galkahana/HummusJS/wiki/Show-primitives) on a [newly created page](https://github.com/galkahana/HummusJS/blob/master/tests/BasicModification2.js#L14)?

Because BT, k, Tf, Tm, Tj, ET
```
pdfWriter.startPageContentContext(page)
                    .BT()
                    .k(0,0,0,1)
                    .Tf(pdfWriter.getFontForFile(__dirname + '/TestMaterials/fonts/Courier.dfont',0),1)
                    .Tm(30,0,0,30,78.4252,662.8997)
                    .Tj('about')
                    .ET();
```
Doesn't seem very familiar to me hahaha

As always, Thank You @galkahana for making such a great plugin!

**Comment by jaspersorrio** [comment]
Also, how do i access [writeText](https://github.com/galkahana/HummusJS/wiki/Show-text) and [drawRectangle](https://github.com/galkahana/HummusJS/wiki/Show-primitives) on a [newly created page?](https://github.com/galkahana/HummusJS/blob/master/tests/BasicModification2.js#L14)

Because BT, k, Tf, Tm, Tj, ET 
```
pdfWriter.startPageContentContext(page)
					.BT()
					.k(0,0,0,1)
					.Tf(pdfWriter.getFontForFile(__dirname + '/TestMaterials/fonts/Courier.dfont',0),1)
					.Tm(30,0,0,30,78.4252,662.8997)
					.Tj('about')
					.ET();
```

Doesn't seem very familiar to me hahaha

**Comment by galkahana** [comment]
Hi @jaspersorrio,
Not sure what you mean by appending a "modified page", but if you want to append a new page to an existing modified document, all you have to do is follow the instructions for creating a new page, in a new doucument.

It will be appended to the existing document at its end.

you can use writeText and drawRectangle with any content context, if it's new page, modified page or a form. what you see here with BT and all are lower level pdf commands. it's just that first i had the lower levels, then figures people would probably prefer something simpler, which is why some of the examples use the old operators.

b.t.w. thanks for your help.

Regards,
Gal.

**Comment by jaspersorrio** [comment]
```
// get first file
let inFilePath = rootDir + '/pdf/test.pdf';
let writer = this.hummus.createWriterToModify(
      new hummus.PDFRStreamForFile(inFilePath),
      new hummus.PDFStreamForResponse(res)
 );
let modifier = new this.hummus.PDFPageModifier(writer,0);

// grab chinese fonts
let font = writer.getFontForFile(rootDir + '/fonts/PingFang.ttc');

// edit first file
modifier.startContext().getContext().writeText(
      '衫仲',
      0, 0,
      {
        font:font,
        size:options.fontSize,
        colorspace:'gray',
        color:0x00
      }
    );

// get second file
let inFilePath2 = auth.rootDir + '/pdf/test2.pdf';
let writer2 = this.hummus.createWriterToModify(
      new hummus.PDFRStreamForFile(inFilePath),
      new hummus.PDFStreamForResponse(res)
 );
let modifier2 = new this.hummus.PDFPageModifier(writer2,0);

// grab english fonts
let font = writer2.getFontForFile(rootDir + '/fonts/roboto-regular.ttc');

// edit second file
modifier2.startContext().getContext().writeText(
      'test',
      0, 0,
      {
        font:font,
        size:options.fontSize,
        colorspace:'gray',
        color:0x00
      }
    );

// how to append second file/pdf to first file/pdf?

```

**Comment by galkahana** [comment]
I see.
Well, you could , save the second PDF and then append it to the original. using `writer. appendPDFPagesFromPDF`

But i have a better offer. it will save some roboto representations and the requirement to create the 2nd file.
how about you after modifying the first page do this:
1. create a new page
2. merge the 2nd pdf page with the new page (mergePDFPagesToPage). alternatively you can import it as a form and place it (createFormXObjectsFromPDF).
3. writeText on top of it.

Gal.

**Comment by jaspersorrio** [comment]
Hi @galkahana,

I agree your solution is better!! Now how do i make use of the high level methods?

e.g.
```
// LOAD FIRST FILE
let inFilePath = __dirname + '/pdf/Blank SanTeong.pdf';

let pdfWriter = hummus.createWriterToModify(
    new hummus.PDFRStreamForFile(inFilePath),
    new hummus.PDFStreamForResponse(outputResponseStream)
);

// GET MODIFIER
let pdfModifier = new hummus.PDFPageModifier(writer, 0);

// WRITE TEXT
pdfModifier.startContext().getContext().writeText(
    'text',
    0, 0, {
        font: pdfWriter.getFontForFile(auth.rootDir + '/fonts/roboto-regular.ttf'),
        size: 9,
        colorspace: 'gray',
        color: 0x00
    }
);

pdfModifier.endContext().writePage();

// CREATE NEW PAGE

let page = pdfWriter.createPage(0, 0, 595, 842);

let font = pdfWriter.getFontForFile(auth.rootDir + '/fonts/roboto-regular.ttf');

// ---- How do i use writeText method here instead of use BT, k, Tf, Tm

pdfWriter.startPageContentContext(page)
    .BT()
    .k(0, 0, 0, 1)
    .Tf(font, 1)
    .Tm(30, 0, 0, 30, 78.4252, 662.8997)
    .Tj('about')
    .ET();

pdfWriter.writePage(page);
```
[TEST.pdf](https://github.com/galkahana/HummusJS/files/472153/TEST.pdf)

**Comment by galkahana** [comment]
`pdfWriter.startPageContentContext(page)` returns a content context, like 
`pdfModifier.startContext().getContext()`

so just replace BT and the rest with writeText call.
it's the same type of object.

Gal.

**Comment by jaspersorrio** [comment]
Hi @galkahana!

Thank you for helping me trouble shoot my issue!

I got it generated quite nicely! 

Once again, thank you for your library and awesome support (:
