### ISSUE TITLE
Crash/hang when modifying an added page

### ISSUE THREAD

**Issue by storafrid** [galkahana/HummusJS#105]
I want to create a new PDF, import a page from another PDF (which acts as a template) and then add some text on top of the imported page. So that the end result is a PDF with one page, consisting of two things: The template PDF (as a background) and my text addition. It should be a common use case, but I've struggled for some time now with this.

The crash/hang is on `pageModifier.startContext()`.
```
var hummus = require('hummus');
var writer = hummus.createWriter('./output.pdf');

writer.appendPDFPagesFromPDF('./template.pdf');

var pageModifier = new hummus.PDFPageModifier(writer, 0);
var pageContextStart = pageModifier.startContext(); // ERR
pageContextStart.getContext().writeText(
    'Test text',
    70, 10,
    { size: 10 }
);
pageModifier.endContext().writePage();
writer.end();
```

**Comment by galkahana** [comment]
Hi,
the example [here](https://github.com/galkahana/HummusJS/blob/master/tests/ModifyExistingPageContent.js) implements the use-case that you have in mind. 
no need to append the page, you can simply created a modified copy of the template, with whatever name you want, and modify the first page, adding the desired text.

In the script that you wrote you are:
1. creating a PDFPageModifier on writer which points to a new pdf, and not one that is modified, hence the crash.
2. you should also note a certain font when using writeText, with which the text is to be written. unexpected if you dont

If you insist on creating a new page than what you could do is to create a new page, merge the original page content into the new page, and add your text on top of it.
there's a code example that you can try here:
https://github.com/galkahana/HummusJS/blob/master/tests/MergePDFPages.js#L40
the merging option is explained here:
https://github.com/galkahana/HummusJS/wiki/Embedding-pdf#merging-a-page-content-to-another-page-content


Using the copying context, like in [this](https://github.com/galkahana/HummusJS/blob/master/tests/MergePDFPages.js#L141) example will provide you with the template document parser (get it via `cpyCxt.getSourceDocumentParser()`), which then can give you the originial page dimensions, if you need them.

Gal.

**Comment by storafrid** [comment]
Thank you, unfortunately I did already try your suggestion and my problem persisted. It fails when creating the second page using this technique. I was trying to not include all of the complexity I have. Hopefully this extended sample will clarify my problem.

If I enable the lines from `var pageModifier = new hummus.PDFPageModifier(writer, 1);`, then the process hangs at that line. When those lines are disabled however, a second page (from the template) is added correctly.

```javascript
var connect = require('connect');
var hummus = require('hummus');

connect().use('/', function (req, res) {
    res.writeHead(200, {
        'Content-Type': 'application/pdf',
        'Access-Control-Allow-Origin': '*'
        //'Content-Disposition': 'attachment; filename=NiceName.pdf'
    });
    var inStream = new hummus.PDFRStreamForFile('./template.pdf');
    var outStream = new hummus.PDFStreamForResponse(res);
    var writer = hummus.createWriterToModify(inStream, outStream);
    var arial = writer.getFontForFile('./arial.ttf');

    // Page 1
    var pageModifier = new hummus.PDFPageModifier(writer, 0);
    var pageContext = pageModifier.startContext().getContext();
    pageContext.writeText('ONE', 1, 1, { font: arial, size: 11 });
    pageModifier.endContext().writePage();

    // Page 2
    writer.appendPDFPagesFromPDF('./template.pdf');
    //var pageModifier = new hummus.PDFPageModifier(writer, 1);
    //var pageContext = pageModifier.startContext().getContext();
    //pageContext.writeText('TWO', 2, 2, { font: arial, size: 22 });
    //pageModifier.endContext().writePage();

    writer.end();
    res.end();
}).listen(3000);
```

I feel like there is something about the lifecycle that I haven't understood yet. Depending on our resolution in this issue, maybe we will be able to improve the documentation. The tests are a good source for documented examples, by the way. Great work.

If you want to run the code: Save as e.g. `test.js`, run `npm install hummus connect` in the same folder, save any PDF as `template.pdf` in the same folder, as well as [an `arial.ttf` font file](https://github.com/galkahana/HummusJS/blob/master/tests/TestMaterials/fonts/arial.ttf). Then run the server using `node test.js` and visit `http://localhost:3000/` in a browser.

**Comment by galkahana** [comment]
just remove writer.appendPDFPagesFromPDF('./template.pdf'). reckoen you should be fine after that.

if you modify a document its pages are already there, no need to append them. just modify.

**Comment by storafrid** [comment]
Hi, sorry but I think you didn't read my post. If I remove that line it still hangs, and I can understand that! Since there is no page `1` to edit. But why does it hang when there is a second page added?

To clarify: The template consists of one page. I want to create a PDF with X number of pages, where all pages are based on the template page. So I need to first append a second page. Works great. And then I want to edit the second page that I just appended, which I can't get to work.

**Comment by galkahana** [comment]
I see. in that case modification is not what you should use.
What you are looking for is to create a form out of the template page.
Then, for each page that you want to create, create a page with whatever size that you want (could be the template page size), and then add whatever content you want on top of it.

approximately something like this:

````
var connect = require('connect');
var hummus = require('hummus');

connect().use('/', function (req, res) {
    res.writeHead(200, {
        'Content-Type': 'application/pdf',
        'Access-Control-Allow-Origin': '*'
        //'Content-Disposition': 'attachment; filename=NiceName.pdf'
    });
    var writer = hummus.createWriter(new hummus.PDFStreamForResponse(res));
    var arial = writer.getFontForFile('./arial.ttf');

    // create a copying context
    var cpyCxt = writer.createPDFCopyingContext('./template.pdf');
    // parse the first and only page info, so we can get the page dimensions
    var pageInfo = cpyCxt.getSourceDocumentParser().parsePage(0);
    // create a form from the first page
    var formID = cpyCxt.createFormXObjectFromPDFPage(0,hummus.ePDFPageBoxMediaBox);
    
    // Page 1
    var page = writer.createPage();
    page.mediaBox = pageInfo.getMediaBox(); // i'm setting media box only for bravity, you can also set the artBox, bleedBox etc.
    writer.startPageContentContext(page)
        .doXObject(page.getResourcesDictionary().addFormXObjectMapping(formID))
        .writeText('ONE', 1, 1, { font: arial, size: 11 });
    writer.writePage(page);

    // Page 2
    var page = writer.createPage();
    page.mediaBox = pageInfo.getMediaBox(); // i'm setting media box only for bravity, you can also set the artBox, bleedBox etc.
    writer.startPageContentContext(page)
        .doXObject(page.getResourcesDictionary().addFormXObjectMapping(formID))
        .writeText('TWO', 2, 2, { font: arial, size: 22 });
    writer.writePage(page);

    writer.end();
    res.end();
}).listen(3000);
````

some reference, in the case that you may want to explore options around this:

1. copying context (when you want to copy elements of a certain origin PDF to a result PDF with some useful convenience methods like creating a form from a page, or just appending pages) - https://github.com/galkahana/HummusJS/wiki/Embedding-pdf#advanced-pdf-embedding-with-documentcopyingcontext

2. parsed pages data - https://github.com/galkahana/HummusJS/wiki/Parsing#page-info-objects

3. using forms - https://github.com/galkahana/HummusJS/wiki/Reusable-forms (i'm creating a form in the code, rather than just merging the template content. it is more efficient to create,  creates a smaller end result and quite a lot of printers can optimize if you place forms on pages).

Gal.

**Comment by storafrid** [comment]
I can't say I understand why or what yet, but thank you! I will read more and try to understand why my first approach was incompatible with the way the library works.
