### ISSUE TITLE
Using Standard Fonts without embedding

### ISSUE THREAD

**Issue by vedat-keklik** [galkahana/HummusJS#114]
Hi,

Is there a way to use standard PDF fonts (Helvetica, Times-Roman etc.) when adding text to pages? It seems embedding is the only option right now. But I don't want to use it for a reason. 

Thanks.

**Comment by galkahana** [comment]
there's an option in the C++ version of hummus to allow avoiding font embedding. its not exposed in hummusJS for no real reason but it not being done.
So one option to accomplish what you want is to expose this parameter in hummusJS and use it.

Another option is to use the standard 14 PDF fonts with the low level text placement methods of hummusJS. 
low level operators match PDF operators. you can find an example here:
https://github.com/galkahana/HummusJS/blob/master/tests/SimpleTextUsageTest.js

here for documentation in the C++ library (names are matching to JS): 
https://github.com/galkahana/PDF-Writer/wiki/Text-support#low-level-text-commands

you will need to use `Tf` and `Tj` in their "low" mode.
Provide the standard font name ('Helvetica') as the first parameter to `Tf` to use this variant to set the font.
To place the text use `Tj`, however make sure to use a low level encoding. you will have only latin chars at your disposal. As a second parameter to `Tj` provide an option object with a single key 'encoding' with the value of 'code'. the string should be regular text.

like this:

````
   pdfWriter.startPageContentContext(page)
			.BT()
			.k(0,0,0,1)
			.Tf('Helvetica',1)
			.Tm(30,0,0,30,78.4252,662.8997)
			.Tj('abcd',{encoding:'code'})
			.ET()
````

**Comment by vedat-keklik** [comment]
Thanks for the answer. I'll try.
