### ISSUE TITLE
PDF Information parsing problem

### ISSUE THREAD

**Issue by vedat-keklik** [galkahana/HummusJS#117]
Hi,

I am using your information parsing code in [ParseInfo.js](https://github.com/galkahana/HummusJS/blob/02730266893d288ac6a88148c8f624c41519236e/tests/ParseInfo.js). 

```js
var pdfReader = hummus.createReader(__dirname + '/TestMaterials/SettingInfoValues.pdf');
var info = pdfReader.queryDictionaryObject(pdfReader.getTrailer(), "Info").toJSObject();
```
part is working as expected. I changed rest of code as below:
```js
assert.equal(info.Author.value, 'Gal Kahana', 'author value');
assert.equal(info.Author.toText(), 'Gal Kahana', 'author decoded');
assert.equal(info.Author.value, 'Gal Kahana', 'creator value');
assert.equal(info.Author.toText(), 'Gal Kahana', 'creator decoded');
assert.equal(info.CreationDate.value, 'D:20140720204655+03\'00\'', 'creation date value');
```
to

```js
Object.keys(info).forEach(function(key){
      info[key]=info[key].value
});
console.log(info);
```
And the result is:
```js
{ 
  CreationDate: undefined,
  Creator: undefined,
  ModDate: undefined,
  Producer: undefined,
  Title: undefined 
}
```

I made another test. `Object.keys(info)` part is commented out. Result:

```js
{ 
  CreationDate: PDFIndirectObjectReference {},
  Creator: PDFIndirectObjectReference {},
  ModDate: PDFIndirectObjectReference {},
  Producer: PDFIndirectObjectReference {},
  Title: PDFIndirectObjectReference {} 
}

```

In short, I couldn't be able to access to attributes of parsed information via using `value` or `toText()`. Both returns `undefined`.

Thanks.

**Comment by galkahana** [comment]
The 2nd test shows that the info dictionary does not hold its values directly. Rather each dictionary value holds a reference (`PDFIndirectObjectReference`) to another object which holds the actual value. You can alter your code a little bit to be able to handle both cases where values are direct and indirect by using `queryDictionaryObject`:

````
var infoDict = pdfReader.queryDictionaryObject(pdfReader.getTrailer(), "Info")
var info = infoDict.toJSObject()

Object.keys(info).forEach(function(key){
      info[key]=pdfReader.queryDictionaryObject(infoDict,key).value
});
````

**Comment by vedat-keklik** [comment]
It works, many thanks.
