### ISSUE TITLE
HummusJS produces corrupt PDFs

### ISSUE THREAD

**Issue by porst17** [galkahana/HummusJS#124]
I am on MacOS 10.11.6 with nodejs 6.5.0 (bundled with Electron 1.4.11) and so far all of my attempts to create PDFs using HummusJS 1.0.65 failed. PDF files get created, but PDF viewers tell me that the files are corrupt. I can reproduce this using very basic PDF operations found in the HummusJS test cases.

[tests/EmptyPagesPDF.js](https://github.com/galkahana/HummusJS/blob/master/tests/EmptyPagesPDF.js) results in [4EmptyPages.pdf](https://github.com/galkahana/HummusJS/files/643634/4EmptyPages.pdf).
[tests/SimpleContentPageTest.js](https://github.com/galkahana/HummusJS/blob/master/tests/SimpleContentPageTest.js) results in [SimpleDrawing.pdf](https://github.com/galkahana/HummusJS/files/643635/SimpleDrawing.pdf).

Both tests don't throw an error, but the results are not usable.

I tested with Preview and Adobe Reader on MacOS X and Evince on Ubuntu Linux. Preview and Adobe Reader complain about corrupt files. For [SimpleDrawing.pdf](https://github.com/galkahana/HummusJS/files/643635/SimpleDrawing.pdf), Evince outputs this to STDERR:
```
Syntax Error (92): Unknown operator ','
Syntax Error (92): Unknown operator ','
Syntax Error (92): Unknown operator ','
Syntax Error (95): Unknown operator ','
Syntax Error (95): Too few (0) args to 'k' operator
Syntax Error (92): Unknown operator ','
Syntax Error (92): Unknown operator ','
Syntax Error (92): Unknown operator ','
Syntax Error (95): Unknown operator ','
Syntax Error (95): Too few (0) args to 'k' operator
Syntax Error (92): Unknown operator ','
Syntax Error (92): Unknown operator ','
Syntax Error (92): Unknown operator ','
Syntax Error (95): Unknown operator ','
Syntax Error (95): Too few (0) args to 'k' operator
Syntax Error (92): Unknown operator ','
Syntax Error (92): Unknown operator ','
Syntax Error (92): Unknown operator ','
Syntax Error (95): Unknown operator ','
Syntax Error (95): Too few (0) args to 'k' operator
Syntax Error (92): Unknown operator ','
Syntax Error (92): Unknown operator ','
Syntax Error (92): Unknown operator ','
Syntax Error (95): Unknown operator ','
Syntax Error (95): Too few (0) args to 'k' operator
```

**Comment by galkahana** [comment]
This has to do with the locale that your computer is setup with, i'm assuming German, and an incompatibility of such setup with the underlying lib.

no worries. think I fixed that. try the new hummusjs (1.0.66), let me know if it fares better (couldn't recreate the problem after a while, so i'd love your feedback).

Gal.

**Comment by porst17** [comment]
Yes, my locale is German (`LANG="de_DE.UTF-8"`). I updated to HummusJS 1.0.66 and the PDFs seem to be OK now. Thank you very much, also for your prompt reply and fix!

**Comment by galkahana** [comment]
:)
