### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by maxtotterman** [galkahana/HummusJS#127]
Hi this is not a issue per se.
I've been trying to create a image 2 pdf converter, and been using lots of different libs. Which kinda sucks.

I just stumbled upon this library and it looks promising, kinda lost on the documentation though.
But what I'm looking for is taking a picture of some type(mostly png,jpg,tiff) as a buffer and convert it to a PDF.

I'm, just wondering. Can this library do this? To convert image buffers to PDF buffers? And maybe even take doc, txt files and convert it to a PDF buffer?

I have my own PDF merger, but I've seen that this library also does this so I may even switch to HummusJS.

Thanks :)

**Comment by galkahana** [comment]
Hummus is able to generate PDFs either as files or buffers. When it comes to image import, Hummus supports JPGs, Tiffs and other PDFs. importing is possible as either files or seekable buffers (most of the readable streams are not, but you can read them to memory buffers and use them instead). As far as I understand whoever wants to use other image formats or documents (or utilize transparency in tiffs, which is not supported) will use another library to create a PDF file/stream and import it to Hummus. 
[Pretty much everything you need to know about images support in Hummus is described [here](https://github.com/galkahana/HummusJS/wiki/Show-images)]

When it comes to manipulating an existing PDF, splitting, merging whatnot, Hummus is a good goto, being quite powerful in that area. So merging shouldn't be a problem.

**Comment by maxtotterman** [comment]
Alright, kinda late reply. But thank you for your reply! 👍
