### ISSUE TITLE
Node InternalFieldCount() > 0 Assertion Failed

### ISSUE THREAD

**Issue by tbezman** [galkahana/HummusJS#128]
`Assertion failed: (handle->InternalFieldCount() > 0), function Wrap, file /Users/Terence/IdeaProjects/nyp-waste-filler/node_modules/electron-rebuild/lib/headers/.node-gyp/iojs-1.4.13/src/node_object_wrap.h, line 56.`

Hey, wanna start by thanking you for this awesome project. This error occurs when I try to create a PDFPageModifier. Not sure what's going on, it seems to be a problem with iojs. Is there a specific version of node you're using? I'm using 6.9.2

**Comment by galkahana** [comment]
I'm building hummus with 0.10,0.12,4.0,4.2,5.12,6.3, and they seems to work fine.

Maybe 6.9.2 contains some change in V8 that we're to tackle.

If another version doesn't work for you, let's try to pinpoint this.
Can you please share a sample script that fails?

Gal.

**Comment by galkahana** [comment]
and environment description, like OS etc.

**Comment by tbezman** [comment]
Hey, busy week at work. Due to time constraints I had to end up choosing a horrible method to fill out these pdfs. I'm no longer using hummus and don't think I can contribute. I think the issue should be closed, unless you would like to further investigate.

**Comment by galkahana** [comment]
i will close it until i have something reproducable.  Thanks for letting me know.

**Comment by KernelDeimos** [comment]
I've been able to reproduce this error by calling `hummus.PDFPageModifier` as a function and forgetting the `new` keyword
