### ISSUE TITLE
Replace a word with image in existing PDF

### ISSUE THREAD

**Issue by abhijitborade** [galkahana/HummusJS#130]
I have put some text e.g. CUST_SIGN, AGENT_SIGN, etc. wherever I need signatures in the document. Please help me finding coordinates of the text exactly matching the text. 

Or suggest me some other method to overlap the text with a signature image. 

Thank you.

**Comment by galkahana** [comment]
Getting text coordinates is quite hard. there's no high level method with hummus and you'll have to dig in a bit into PDF to figure out the text coordinates.
If you want exactly that - try other solutions, or there's quite a bit of work here.

Alternatively, use something that would make it simpler to find its position - like annotations.
could this work for you?

Gal.

**Comment by abhijitborade** [comment]
@galkahana Can I get coordinates of annotations? If yes that will be great.

**Comment by galkahana** [comment]
That's how it works with annotations.
Each page dictionary holds it annotations in an entry that's called "Annots".
Then each such annotation holds its position on the page in its "Rect" entry.
