### ISSUE TITLE
write on second page

### ISSUE THREAD

**Issue by romainkoenig** [galkahana/HummusJS#131]
Hello I have used your package to write some text on a existing PDF and it works well.
Today I added a second page and I tried to modify it. But I am not sure how to to that.
````js
  res.setHeader('Content-disposition', `attachment; filename=name.pdf`);
  res.writeHead(200, { 'Content-Type': 'application/pdf' });
  // Hummus packages :
   const pdfWriter = hummus.createWriterToModify(
    new hummus.PDFRStreamForFile(`${dirPath}/mypdf.pdf`),
    new hummus.PDFStreamForResponse(res));

  const style = {...};

  const pageModifier = new hummus.PDFPageModifier(pdfWriter, 0);
  for (const input of data) {
    pageModifier.startContext().getContext().writeText(
      input.text, input.pointX, input.pointY, style);
  }
  pageModifier.endContext().writePage();
  pdfWriter.end();

  res.end();
````
When I set ( X : 0, Y : 0 ) I got the text at the very bottom left of the page ( origin of the axis ). So I naively put some negative value in the Y axis, but with no success. I couldn't find a 'page' parameter on the writeText function neither.
Do you know if that behavior is possible ?  Or should I find an other way ?

**Comment by galkahana** [comment]
1. Coordinate in hummus are like in PDF which are cartesian. want the text at the top of the page? put it at x:0,y:-textHeight

2. Not sure about "'page' parameter" or  "i added a second page and tried to modify it", but i'll tell you this - if you are trying to add a new page to a document that you are modifying, then don't use "hummus.pdfPageModifier". its purpose is to modify pages that existed in the document already, and not those that you'll want to add. any pages that you add to modified document you don't need to modify - just write them as intended. here is an example of adding a new page - https://github.com/galkahana/HummusJS/blob/master/tests/BasicModification2.js

**Comment by romainkoenig** [comment]
Hello, thanks for the quick response.
For me the (0.0) coordinates correspond to the bottom left of the first page. When I increment the Y coordinates the text goes up. When I put a negative number, the text disappears and is not on the second page as I thought. Maybe there is something wrong with my PDF/version or code, but it seems you confirm that the normal behavior is to see the text at the top of the second page for example, it's not a normal limitation of the library, is it ? 

I tried several ways like adding and modifying or the contrary. But I think the simplest is to have an already existing PDF of two pages ( with all the forms ) and then modifying it with the input and then send it. ( I also use streams ). I do not concatenate it in my app.

**Comment by galkahana** [comment]
Oh friend. there's a big misunderstanding here.
no limitation exists in the code.
There is no inter-page coordinate system. coordinate system is within the page itself.
want to write on the second page? start a page modifier on the second page (index 1), and write using 0,0 as the 2nd page bottom left.

makes sense?

**Comment by romainkoenig** [comment]
Oh yes... I see it now, I wasn't focusing on the good function 
````js
const pageModifier = new hummus.PDFPageModifier(pdfWriter, 1); // <- 1 !!!
````
is what I was searching for ! Thanks for your time ...

**Comment by balashanmugam** [comment]
> Oh friend. there's a big misunderstanding here.
> no limitation exists in the code.
> There is no inter-page coordinate system. coordinate system is within the page itself.
> want to write on the second page? start a page modifier on the second page (index 1), and write using 0,0 as the 2nd page bottom left.
> 
> makes sense?

Yes and it saved me!
