### ISSUE TITLE
Running on Heroku

### ISSUE THREAD

**Issue by ryhinchey** [galkahana/HummusJS#135]
Hi There - first off, thanks for writing such an awesome library.  I really appreciate it and thanks for putting it out in the world.

I'm running a node.js app and am using Hummus to modify an existing PDF.  It works beautifully on my local machine.

I'm trying to deploy my app to Heroku and when I include Hummus, all of my requests time out on Heroku's end.  I can confirm that when I don't include Hummus, the app works as expected (besides the PDF generation part obviously)

Does anyone here have any experience or advice for getting Hummus to run on Heroku?  I've been looking for a C++ buildpack but haven't found anything that Heroku supports. 

I tried adding this to my package.json scripts, which didn't work:
```
"heroku-postbuild": "npm install --build-from-source=hummus"
```

**Comment by ryhinchey** [comment]
I'm going to close this issue since it's not really an issue in the first place.  Thanks again for the great library!

**Comment by galkahana** [comment]
How did you resolve the problem?

**Comment by ryhinchey** [comment]
@galkahana no I couldn't figure out how to get the C++ implementation running on Heroku. I  ended up writing it in python
