### ISSUE TITLE
Problems to Edit PDF file

### ISSUE THREAD

**Issue by jhonnynho** [galkahana/HummusJS#139]
I have this code

```
var pdfWriter =  hummus.createWriterToModify(__base + 'existing.pdf', {
log: __base + 'hummus.log',
modifiedFilePath: __base + 'existing.pdf'
});
var cpyCxt = pdfWriter.createPDFCopyingContext(pdfWriter);
var imageXObject = pdfWriter.createImageXObjectFromJPG('./logo.jpg'); 
    for (var i=0; i < pdfWriter.getPagesCount(); ++i) {
        var formObjectId  =  cpyCxt.createFormXObjectFromPDFPage(i, hummus.ePDFPageBoxMediaBox);
        var pageInfo =  pdfWriter.parsePage(i);
        var dimensions = pageInfo.getMediaBox();
        var oldWidth = 595;
        var oldHeight = 842;
        if(dimensions && dimensions[2]){
            oldWidth = dimensions[2];
        }
        if(dimensions && dimensions[3]){
            oldHeight = dimensions[3];
        }
        var imageHeight = 20;  // Height of the footer image
        var newHeight = oldHeight-imageHeight;
        var page = pdfWriter.createPage(0,0,595,842);
        var pageContent = pdfWriter.startPageContentContext(page);
        pageContent.q()
            .cm(newHeight/oldHeight,0,0,newHeight/oldHeight,5,imageHeight)
            .doXObject(page.getResourcesDictionary().addFormXObjectMapping(formObjectId))
            .Q();
        pageContent.q()
            .cm(130,0,0,13,225,4) //width, rotation angel ,rotation angel, height, left, bottom .   Placement of the footer logo.
            .doXObject(imageXObject)
            .Q();
        pdfWriter.writePage(page);
    }
    pdfWriter.end();
```

In Log appears this errors

```
[ 28/01/2017 20:21:36 ] PDFParser::ParseHeaderLine, no tokens in PDF input. in other words - it's empty.
[ 28/01/2017 20:21:36 ] PDFDocumentHandler::StartCopyingContext, failure occured while parsing PDF file.
```

Any idea? Thanks

**Comment by galkahana** [comment]
Sounds like the pdf file is empty.

**Comment by jhonnynho** [comment]
Impossible, I tested with distinct PDF files with content!

**Comment by jhonnynho** [comment]
Hi, this code works for me but if I use the same PDF to Write and Read, this functions add the same pages of a PDF after the last page with images! How I can add images in the same PDF without copying the pages?

**Comment by galkahana** [comment]
cool.
i noticed some weird things about the code. pdfWriter is used as a parser sometimes (for example, when creating a copying context), which should fail. i'm assuming that this is some sort of pseudo code, cause it shouldn't be running correctly.
in addition the line that does "var cpyCxt = pdfWriter.createPDFCopyingContext(pdfWriter);" should instead use "var cpyCxt = pdfWriter.createPDFCopyingContextForModifiedFile()". this should avoid heaps of trouble, and unnecessary copying. plus no way pdfWriter.createPDFCopyingContext(pdfWriter) should work as createPDFCopyingContext expects either a file input or a parser.

if this is not pseudo code, then i guess these are matters that require corrections in this code.

makes sense?
Gal.

**Comment by jhonnynho** [comment]
Hi Gal. 

I need the code to add an image to the bottom of each page, as it is this code copies the pages of the PDF at the end with the images.

This code I found on the net, I think it makes copies is by these lines

Var page = pdfWriter.createPage (0,0,595,842);
Var pageContent = pdfWriter.startPageContentContext (page);

I dont want to add copy of pages on the same PDF I only want to add images in all pages of PDF without generate copies

Any idea what I should do? Many thanks!

**Comment by galkahana** [comment]
How about trying something more like the original code in #98. specifically don't use a modifying writer - createWriterToModify - but a new fresh writer.

what you are doing right now is to take an existing PDF and append pages to it.
instead create a new PDF with  a regular createWriterToModify. Then create a copying context to the original file and run the code. This is how the other guy was doing that.

Will this be good?

**Comment by jhonnynho** [comment]
Hi Gal

I made this

```
var writer = hummus.createWriterToModify(__base + 'existing.pdf', {
            modifiedFilePath: __base + 'existing.pdf'
        });
        var pdfReader = hummus.createReader(__base +"existing.pdf");
        for (var i=0; i < pdfReader.getPagesCount(); ++i) {
            var pageModifier = new hummus.PDFPageModifier(writer, i, true);
            var pageTop = writer.getModifiedFileParser().parsePage(0).getMediaBox()[1];
            var imageHeight = 20;
            pageModifier.startContext().getContext().drawImage(0, 0, __base +'logo.jpg',{transformation:{width:790,height:95}});
            pageModifier.endContext().writePage();
        }
        writer.end();
```
This helps me to modify the same PDF without adding copies of the pages.

Thanks for help. Excuse me my bad englihs and if you dont understand me

**Comment by jhonnynho** [comment]
Hi Gal, I Again

I have other question.

The code that I pasted in the last comment works for me. I can add the images in the footer.

The images that I add in the footer contains these dimensions 790 width and 95 height, but this images do not cover the width of the page, only covered up to half

Do you know some form of occupying the full width?

I added an image of how the PDF is left. Many thanks again!

![banner](https://cloud.githubusercontent.com/assets/13169828/22411899/28ead69a-e67f-11e6-9ad6-66d597f67c11.png)

**Comment by galkahana** [comment]
No worries about the english, ain't my native lang as well. as long as we are able to succeed we're happy. You can try some spanish on me, but it's been a while since i used that, so let's keep it in english.

You can do that with a different transformation parameter.
let's start by cleaning the code a bit, cause there's bits that are not used. the is a clean version of it:
     
    var writer = hummus.createWriterToModify(__base + 'existing.pdf', {
            modifiedFilePath: __base + 'existing.pdf'
        });
    var pdfReader = writer.getModifiedFileParser();
     for (var i=0; i < pdfReader.getPagesCount(); ++i) {
            var pageModifier = new hummus.PDFPageModifier(writer, i, true);
            pageModifier.startContext().getContext().drawImage(0, 0, __base +'logo.jpg');
            pageModifier.endContext().writePage();
     }
     writer.end();

as is, the image will be drawn according to its existing dimensions. as you say - 790*95.

We want to scale it so that it covers the width of the page. 
First, let's figure out the width of the page.
Place the following code at the beginning of the loop code:

    var pageBox = pdfReader.parsePage(i).getMediaBox();
    var pageWidth = pageBox[2] - pageBox[0];

Now. what we want is to have the image cover the width of the page. as for the image height, i guess that you would like to keep it proportional to the original image intention.
So if the new width is `pageWidth` the new height should be `originalHeight * pageWidth/originalWidth'.

Let's figure out the original dimensions then:

    var imageDimensions = pdfWriter.getImageDimensions(__base +'logo.jpg'); 

that should give us `imageDimensions.width` and `imageDimensions.height`.
Now let's just tell hummus to draw the image using the new dimensions:

    pageModifier.startContext().getContext().drawImage(0, 0, __base +'logo.jpg',
       {transformation:{
                  width:pageWidth,
                  height:pageWidth*imageDimensions.height/imageDimensions.width,    
                  fit:'always'}});

the transformation parameter causes the drawing to fit itself to the desired new box. we must tell it to fit 'always' because otherwise if the image is originally smaller than the new box, it will leave it as is.

Now let's see the whole thing together:

    var writer = hummus.createWriterToModify(__base + 'existing.pdf', {
            modifiedFilePath: __base + 'existing.pdf'
        });
    var pdfReader = writer.getModifiedFileParser();
     for (var i=0; i < pdfReader.getPagesCount(); ++i) {
            var pageBox = pdfReader.parsePage(i).getMediaBox();
            var pageWidth = pageBox[2] - pageBox[0];
            var imageDimensions = pdfWriter.getImageDimensions(__base +'logo.jpg'); 

            var pageModifier = new hummus.PDFPageModifier(writer, i, true);
            pageModifier.startContext().getContext().drawImage(0, 0, __base +'logo.jpg',
                {transformation:{
                      width:pageWidth,
                      height:pageWidth*imageDimensions.height/imageDimensions.width,    
                      fit:'always'}});
            pageModifier.endContext().writePage();
     }
     writer.end();

**Comment by jhonnynho** [comment]
This works perfectly for me Gal. Thank you so much!

**Comment by jos1337** [comment]
Im sorry if this is the wrong place, I'm new to being active on github, dont know where else to ask.
I have trouble to use ur snippet from above. It working fine to copy pdfs but as soon as i add the part where the image is being added it get: TypeError: Unable to end PDF
Is there a way to debug the problem? I also tried different images/imagepaths. 
Any ideas how i could solve this?

**Comment by galkahana** [comment]
Attach here sample code anf some sample files, and ill be able to look into this.

**Comment by jos1337** [comment]
thank you!
i have both files in /tmp/filename, then i did more or less copy and paste the code above:

var source = path.resolve(pdfsourse);
var dest = path.resolve(pdfdest);
var qrwithpath = path.resolve(qrfile);

var pdfWriter = hummus.createWriterToModify(source, {
        modifiedFilePath: dest
    });
var pdfReader = pdfWriter.getModifiedFileParser();
 for (var i=0; i < pdfReader.getPagesCount(); ++i) {
        var pageBox = pdfReader.parsePage(i).getMediaBox();
        var pageWidth = pageBox[2] - pageBox[0];
        var imageDimensions = pdfWriter.getImageDimensions(qrwithpath); 

        var pageModifier = new hummus.PDFPageModifier(pdfWriter, i, true);
        pageModifier.startContext().getContext().drawImage(10, 50, qrwithpath,
            {transformation:{
                  width:pageWidth,
                  height:pageWidth*imageDimensions.height/imageDimensions.width,    
                  fit:'always'}});
        pageModifier.endContext().writePage();
 }
 pdfWriter.end();

---
I also tried some other solutions, but i got another problem which I cant solve:
when i try to do this:
    var imageXObject = pdfWriter.createImageXObjectFromJPG(qrwithpath);
my node is freezing without error. maybe this is caused by the same issue.
appended some testfiles.
thank you again.

[testpdf.pdf](https://github.com/galkahana/HummusJS/files/991347/testpdf.pdf)
![qr](https://cloud.githubusercontent.com/assets/26776579/25923338/46fd97d2-35dd-11e7-8db4-357e141ee1cf.jpg)

**Comment by jos1337** [comment]
I added some logging:
[ 11/05/2017 09:52:39 ] ObjectsContext::WriteXrefTable, Unexpected Failure. Object of ID = 27 was not registered as written. probably means it was not written
[ 11/05/2017 09:52:39 ] PDFWriter::EndPDF, Could not end PDF

**Comment by jos1337** [comment]
i did manage to get it running. there have been some timing problems with the image creating. 
its working now, even with passwordprotection. i have another question:
is it possible to prevent users from copying content out of the pdf with userProtectionFlag and to which value do i have to set it? 
thank you and sorry for bothering you.

**Comment by johshej** [comment]
Hi jos1337.
May I ask what kind of timing problems you were haveing and how you resolved them. I'm getting the "TypeError: Unable to end PDF" probably in connection with adding a tiff on each page of a pdf.
The odd thing is that it's working when I run it locally, but not, when I run it on a test-server.

**Comment by jos1337** [comment]
Im afraid i cant really help here. in my case it solved my issue when i changed my code to a lot of chained promisses.
You could post some code, maybe someone can help you than.
