### ISSUE TITLE
How to add text to an existing PDF

### ISSUE THREAD

**Issue by SantoshSrinivas79** [galkahana/HummusJS#15]
I tried various combinations but finding it difficult to get the context correct for an existing page in an existing pdf.

I am basically trying to add a small text to an existing page in an existing pdf.

Can you please suggest how to do the same that you have in `TextMeasurementsTest.js` to an existing file.

I have an existing simple pdf with two pages and want that text to be added to the second page

**Comment by elgubenis** [comment]
can images also be added to existing pages?

**Comment by galkahana** [comment]
see #82. My last comment has a sample script. the required materials are provided earlier.

Gal.
