### ISSUE TITLE
annotation properties

### ISSUE THREAD

**Issue by chunyenHuang** [galkahana/HummusJS#150]
Hello Gal,
Do you know where I can find more about the properties/keys for pdf annotations? 
In your example, [PDFcomment](https://github.com/galkahana/HummusJS/blob/02730266893d288ac6a88148c8f624c41519236e/tests/ModifyingExistingFileContent.js), there are `Type`, `Subtype`, `Rect`, `C`, `T`, `M`... However, I only know others like `RC`, `Subj`. Is there a list for all of these keys?

Thanks so much~

**Comment by galkahana** [comment]
Pdf manual - http://pdfhummus.com/Downloads

**Comment by chunyenHuang** [comment]
Thanks so much! found in PDF Reference, version 1.7 Page 616 - Markup Annotations.
