### ISSUE TITLE
Adding textbox/ textfield on existing PDF file.

### ISSUE THREAD

**Issue by cqthanh** [galkahana/HummusJS#151]
Hi Gal,
Can I add a textbox / Text field in the existing PDF file so the users can fill in the necessary information before printing it out? And how to achieve that ? 
Thanks.

**Comment by galkahana** [comment]
that's gonna need adding a form.
not a high level functionality of the library, but could be done.

read about how to create forms in pdf in the pdf reference manual here - http://pdfhummus.com/Downloads
read about low level functions of the library here - https://github.com/galkahana/HummusJS/wiki/Extensibility

**Comment by cqthanh** [comment]
Hi Gal,
Could you give me more details ? I tried to use the low level functions in https://github.com/galkahana/HummusJS/wiki/Extensibility and http://pdfhummus.com/post/45501642143/how-to-extend-the-library-adding-comments-to
but it didn't work.
Many thanks.

**Comment by galkahana** [comment]
details about what?

**Comment by cqthanh** [comment]
About creating the form and adding the text field into the created form. How to set reference to the target page (from form to target page) ? And how to set the position for the text field ? It would be great if there is an example.

Thanks for you support.

**Comment by galkahana** [comment]
I see. I don't have an example for that. you'll have to build this by reading the forms section of the reference manual, and building the relevant elements using the extensibility options.

**Comment by cqthanh** [comment]
I almost done this by using annotations, but now I have a problem: I want the annotation to be locked (cant resize or move), but the content can be modified. When writing dictionary I used:
`dictContext..writeKey('Type')
		.writeNameValue('Annot')
		.writeKey('Subtype')
		.writeNameValue('FreeText')
                .writeKey('F')
		.writeNameValue(8);`
but the writeNameValue method only accepts string type and when I changed to .writeNameValue('8'), the PDF file show error message "Expected number object". So how can I set the key F with value 8 ?

Please help! 
Thank you.

**Comment by galkahana** [comment]
use `objectsContext.writeNumber(8)` instead of `dictContext.writeNameValue()`.  
and don't worry - it's ok that you are using objectsContext here.
sais so towards the end here - https://github.com/galkahana/HummusJS/wiki/Extensibility#writing-dictionaries.

**Comment by cqthanh** [comment]
Thank you, finally I could finish this sh*t :+1: . According to this example https://github.com/galkahana/HummusJS/blob/master/tests/ModifyingExistingFileContent.js (adding comments section), I used "Widget" annotation instead of "Text" + Field dictionary(Widget annotation can be merged with Field Dictionary [See Widget Annotations page 640 - PDF Reference 1.7]). My dictionary somehow like this:
`	dictionaryContext
		.writeKey('Type')
		.writeNameValue('Annot') //Annot
		.writeKey('Subtype')
		.writeNameValue('Widget')// Widget Annotation
		.writeKey('FT') //Fieldtype
		.writeNameValue('Tx')// Textbox type
		.writeKey('DA') //Default appearence
		.writeLiteralStringValue('/F1 10.400000 Tf 0 g')
		.writeKey('T') //Textbox name
		.writeLiteralStringValue('txtBoxName')
		.writeKey('Rect') //Widget position and size(x,y,w,h)
		.writeRectangleValue(inComment.position) // when implementing allow also 4 numbers input
		.writeKey('Q') // Text aligment
	objectsContext
		.writeNumber(1);// 0 - lef; 1 - center; 2 -right`
Hope this help someone has the same issue as me.
And once again, thank you, Gal.
