### ISSUE TITLE
createReader return empty object

### ISSUE THREAD

**Issue by nnnikolay** [galkahana/HummusJS#152]
HI, thanks for your library.

I'm trying to start using it, and now I stuck in the reading part.
I' have following code (taken from documentation)
```
var hummus = require('hummus');
var pdfReader = hummus.createReader('./data/input.pdf');
console.log(pdfReader);
```

but in a terminal, I can see an empty object only
`PDFReader {}`

Therefore, none of mentioned in docs methods are available :( 
am I doing something wrong?

Thanks

**Comment by nnnikolay** [comment]
I just took example from your example repo, and it works :)

**Comment by galkahana** [comment]
fyi. most native objects will return an empty object. most hummus objects are native. wiki should provide you with methods documentation (well, you can always dig into the code but it's less advisable if you are less coherent with C++).
