### ISSUE TITLE
Adding watermark?

### ISSUE THREAD

**Issue by xquangdang** [galkahana/HummusJS#160]
Does Hummus support adding watermark to multi pages PDF? I was searching around but found no solution to add watermark to pdf file in nodejs.

**Comment by galkahana** [comment]
is this helpful:
https://github.com/galkahana/HummusJS/wiki/Modification#adding-content-to-existing-pages

**Comment by xquangdang** [comment]
I try some sample and I finally added some text to a page in a pdf file. 
Does hummus support add image or text with opacity? And how to modify multiple pages? 
My text hide the text below it.

**Comment by galkahana** [comment]
transparency for paths was discussed here - #142 - solution for text should be similar.
adding images - https://github.com/galkahana/HummusJS/wiki/Show-images

iterating pages:

    pdfReader = hummus.createReader('main.pdf')
     for(var i=0;i<pdfReader.getPagesCount();++i){
         // do whatever
     }

modifying pages - read again the link. understand that one of the params is the target page index. use it.

**Comment by xquangdang** [comment]
I checked #142 - but I dont know how to get pdfPage from pdfModifier.
I write this code: 

```javascript
var hummus = require('hummus');

var pdfWriter = hummus.createWriterToModify(__dirname + '/TestMaterials/BasicJPGImagesTest.PDF', {
	modifiedFilePath: __dirname + '/output/BasicJPGImagesTestPageModified.pdf'
});

var objCxt = pdfWriter.getObjectsContext();
var gsId = objCxt.startNewIndirectObject();
var dict = objCxt.startDictionary()
dict.writeKey("type");
dict.writeNameValue("ExtGState");
dict.writeKey("ca");
objCxt.writeNumber(0.5);
objCxt.endLine();
objCxt.endDictionary(dict);

var fontCouri = pdfWriter.getFontForFile('./Couri.ttf');

var pageModifier = new hummus.PDFPageModifier(pdfWriter,0);

var objCxt = pageModifier.startContext().getContext();
	objCxt
		.BT() // Begin Text
		.k(0,0,0,1) // Set Color (CMYK, 0-1)
		.Tf(fontCouri,50) // Text font? Font & size?
		.Tm(1,0,0,1,50,50) // Text Matrix, set to coord 5,20
		.Tj('Deparment') // Show text
		.Tm(1,0,0,1,5,5) // Text Matrix, set to coord 5,5 (to place below previous line)
		.Tj('Page Index ' + 0) // More text
		.ET() // End Text
		.q() // Push Current Matrix
		.cm(1,0,0,1,0,35) // Set Current Matrix - scale to 100% (x and y), translate 0,35
		.Q()
pageModifier.endContext().writePage();

pdfWriter.end();
```
Can you show me how to get gsName?

**Comment by galkahana** [comment]
right....
there's no current way in hummus js to do that, as you cannot get the resources dictionary of the context.

To work around this do the following:
1. create a form xobject, where you can implement the drawing, and get the resoruces dictionary to get gsName. see here for details - https://github.com/galkahana/HummusJS/wiki/Reusable-forms.
it's not written there but you can call myForm. getResourcesDictinary() to get the resources dictionary. then use myResDict. addExtGStateMapping() with the object id of the ExtGState that you created to get gsName

2. place the form in the page using cm and do [see the form usage example in the link above to see details]

**Comment by xquangdang** [comment]
I really appreciate your help. I finally manage to make it work. Fantastic lib.
Btw I'm going to deploy the project on the elastic beanstalk. I wonder if npm package needs any config to work on aws. And one last thing about pdfModifer. Does it have any method to get the width/height or any information about the page?

**Comment by galkahana** [comment]
beanstalk should be fine. the special thing about hummusjs is that it is a binary module, and so requires either a compilation or a download of a ready binary. my experience shows that the provided binaries that hummus has match most beanstalk systems, so there wouldn't be a need for compilation.
in other words - if you see a problem and you think its related to hummusjs, let me know.

as for width/height.
The pdfWriter object that you created has a [getModifiedFileParser()](https://github.com/galkahana/HummusJS/wiki/Modification#pdfwriter-a-la-modification) method which should give you a parser for the modified file. This parser can be used for general [parsing](https://github.com/galkahana/HummusJS/wiki/Parsing) of the file, but also has specific methods for getting [page information](https://github.com/galkahana/HummusJS/wiki/Parsing#page-info-objects).

specifically the media box is what you are looking for.

for example:

```javascript
function getPageDimensions(pdfWriter,pageIndex) {
    var pdfParser = pdfWriter.getModifiedFileParser();
    var pageInfo = pdfParser.parsePage(pageIndex);
    var pageMediaBox = pageInfo.getMediaBox();

    return {
        width:pageMediaBox[2]-pageMediaBox[0],
        height:pageMediaBox[3]-pageMediaBox[1]
    };
}
```

should give you a general purpose method to get the page dimensions of a page by index and the pdfWriter object of a modified pdf file.

**Comment by xquangdang** [comment]
Thank you for your help. I finally resolved my problems.

**Comment by hl-a-k** [comment]
Any can offer demo?

**Comment by gaganmurghai** [comment]
@xquangdang I am working to add images on multiple pages with existing pdf. I am only able to add image at a single time can you please help me in this.

**Comment by gaganmurghai** [comment]
Thanks @xquangdang I will try it.

**Comment by marekweb** [comment]
>there's no current way in hummus js to do that, as you cannot get the resources dictionary of the context.

Is there no way to get the page resource dictionary when using PDFPageModifier?

I'm trying to embed a small source PDF onto a destination PDF as a watermark.

`createFormXObjectFromPDFPage` gives me an ID but I can't find how to obtain the actual XObject reference to use with `doXObject` (is there no access to `getResourcesDictionary`?)

Is there a way to use `createFormXObjectFromPDFPage` and place it with `doXObject`, when modifying a PDF using PDFPageModifier?

**Comment by natnaeltibebu** [comment]
@xquangdang, firstly thanks my question is how can i add a custom watermark for each pdf pages without creating a new one in memory(only using 'input.pdf' and save it)
