### ISSUE TITLE
Text annotations

### ISSUE THREAD

**Issue by mllrjb** [galkahana/HummusJS#165]
I'm trying to get text annotations to work and I think I'm having problems with appearance streams.

I'm able to add a `FreeText` annotation to a page, but it doesn't render properly in most PDF viewers (including Adobe Reader).

I'm trying to add an appearance stream via `FormXObject` (based on [your form values example](https://github.com/galkahana/HummusJSSamples/blob/master/filling-form-values/pdf-form-fill.js) ), but I don't see the annotation afterwards (it seems hidden):

```
function writeAp(pdfWriter, {
  x, y, w, h,
}, text, objId) {

  const xf = pdfWriter.createFormXObject(x, y, w, h, objId);

  xf.getContentContext()
    .RG(0.987, 0.129,  0.146)
    .w(0)
    .q()
    .re(x, y, w, h)
    .W()
    .n()
    .g(0)
    .G(0)
    .w(1)
    .BT()
    .writeFreeCode('/Helv 15 Tf \r\n')
    .rg(0.987, 0.129, 0.146)
    .Td(x, y)
    .Tj(text, { encoding: 'code' })
    .ET()
    .Q();

  pdfWriter.endFormXObject(xf);
}

  const nObjId = objectsContext.allocateNewObjectID()

  const apDict = objectsContext.startDictionary();
  apDict
    .writeKey('N')
    .writeObjectReferenceValue(nObjId);

  objectsContext
    .endDictionary(apDict)
    .endDictionary(dictionaryContext)
    .endIndirectObject();

  writeAp(pdfWriter, {
    x, y, w: textDimensions.width, h: baseDimensions.height
  }, text, nObjId);
```

Full example: https://github.com/mllrjb/hummus-annotation-example

Any ideas?

**Comment by chunyenHuang** [comment]
I have noticed one thing in your `example.js`
https://github.com/mllrjb/hummus-annotation-example/blob/master/example.js#L80
```javascript
// change from this
.writeKey('AP'); 
// to this
.writeKey('C');
```
Than you should be able to see your rectangle annotation. And you may need to recalculate the height.
<img width="1147" alt="screen shot 2017-06-29 at 12 23 16 pm" src="https://user-images.githubusercontent.com/12788155/27706248-c2247c8c-5cc5-11e7-910a-c26e3570aa88.png">

**Comment by mllrjb** [comment]
@chunyenHuang - the `C` entry gives me strange results across various PDF readers.

@galkahana - your fixes to just use `writeText` and correct coordinates fixed it for me. I'm happy to contribute an example back if that's helpful!

```
function writeAp(pdfWriter, {
  w, h,
}, text, objId) {

  const xf = pdfWriter.createFormXObject(0, 0, w, h, objId);

  // draw text starting 1/4 of the way up
  const textY = h / 4;

  xf.getContentContext()
    .writeText(
      text,
      0,
      textY,
      {
        size: fontSize,
        colorspace: 'rgb',
        color: 0xFC2125,
        font: arialFont
      }
    );

  pdfWriter.endFormXObject(xf);
}
```

**Comment by chunyenHuang** [comment]
What are those `strange results across various PDF readers`?
It will be good if you can screen shot and post them here.
