### ISSUE TITLE
Rotate a text

### ISSUE THREAD

**Issue by GautierT** [galkahana/HummusJS#170]
Hi, i'm trying to rotate the context to write some text with `context.writeText()`

I have trouble understanding how `context.cm()` works. (And what the parameters are)

I want to rotate to 270° then go back to normal. How can i do that ?
Thanks!

**Comment by chunyenHuang** [comment]
You might want to check https://github.com/galkahana/HummusJS/issues/167

**Comment by GautierT** [comment]
Thanks !  I missed this issue..
