### ISSUE TITLE
Several bad pdfs and issues

### ISSUE THREAD

**Issue by chunyenHuang** [galkahana/HummusJS#177]
Hello Gal~
I have some pdf files with parsing issues. It will be great if you can spend some time to take a look and inspect them.

1. PDFPageInput::GetRotate, Exception (4294967206), pdf page rotation must be a multiple of 90
[wrong rotation.pdf](https://github.com/galkahana/HummusJS/files/1170477/wrong.rotation.pdf)

1. PDFObjectParser - ParseArray, failure to parse array
[Bad-Font-PDF.pdf](https://github.com/galkahana/HummusJS/files/1170485/Bad-Font-PDF.pdf)

1. PDFParser - ParseFileDirectory,Unexpected object at xref start
[xref error.pdf](https://github.com/galkahana/HummusJS/files/1170487/xref.error.pdf)

1. PDFParser - ParsePagesIDs, unexpected type for a Kids array object, type = Null
[unexpected kids array.pdf](https://github.com/galkahana/HummusJS/files/1170491/unexpected.kids.array.pdf)

1. PDFParser::ReadXrefStreamSegment, unfamiliar entry type. must be either 0,1 or 2
[1 unfamiliar entry type.pdf](https://github.com/galkahana/HummusJS/files/1170502/1.unfamiliar.entry.type.pdf)
[2 unfamiliar entry type.pdf](https://github.com/galkahana/HummusJS/files/1170501/2.unfamiliar.entry.type.pdf)

**Comment by galkahana** [comment]
looked over the file, corrected some elements, submitted them and created 1.0.78 (which includes your earlier PR on forms, thanks for that one).

Details, and what i did with each:
1. Corrected. am allowing now rotations with negative values. also in plain writer. parsing should be fine now.

2. Didn't get the error for parsing array. The xref position and xref itself are faulty. i suggest that you will contact whomever is giving you those files and let them know they are being very naughty. if they are big - they'll have enough firepower to fix it. if they are small - have them fix the PDFs. they contain much garbage after the %%EOF which is fine...i guess...but corrupt xrefs, i would rather not deal with. it will slow the lib down to handle such major exceptions. Acrobat is not happy either.

3. This one Acrobat didn't wanna know. same for hummus. Xref table is in the wrong position and has wrong value. see my note on #2 on how to handle this.

4. This pdf has nulls for the final pages. acrobat is not happy either. I made hummus deal with this a bit more gracefully. trying to call parsePage or created modifiers for null pages will cause an exception. so you can tell something bad is happening. but in general - they should not be there.

5. the issues here are a result of png encoding reading errors. corrected.

you can find the correcton for 1,4,5 in 1.0.78.
