### ISSUE TITLE
Corrupt target PDF embedding source PDF

### ISSUE THREAD

**Issue by Bastian1975** [galkahana/HummusJS#205]
I get a corrupt PDF with the errors
- Missing XObject "img2" (multiple times, with different img-numbers) (German "Fehlt XObject 'img2'")
- missing advanced graphicmode (German: "Fehlt erweiterter Grafikmodus 'OPOFF'")
while placing a source PDF into a newly created PDF.
Both functions cxt.drawImage and createPDFCopyingContext are failing with the same result. Acrobat gives me an alert while opening, that there are errors in the PDF and preflight shows me above reasons.
How can I solve this? Is copyDirectObjectWithDeepCopy worth a try?

**Comment by galkahana** [comment]
i'm gonna need some more details of what you are trying to do. how are you trying to embed? maybe the PDF file as sample? script sample would be nice. then I can figure out what's wrong.

**Comment by Bastian1975** [comment]
Sent you the PDF via mail, this is my sample-code:

var express     = require('express');
var app         = express();
var hummus      = require('hummus');
var pdfWriter       = hummus.createWriter("/tmp/targetPDF.pdf");
var pdfpage         = pdfWriter.createPage(0,0,892,1417);
var cxt = pdfWriter.startPageContentContext(pdfpage);
cxt.drawImage(448,643,"/tmp/test.pdf");
pdfWriter.writePage(pdfpage);
pdfWriter.end();

**Comment by galkahana** [comment]
seems like this works:

````
function createFormAndPlace() {
    var pdfWriter = hummus.createWriter('./helloFormAndPlace.pdf',{log:'./helloDrawImage.log'})
    var pdfpage = pdfWriter.createPage(0,0,892,1417);
    var cxt = pdfWriter.startPageContentContext(pdfpage);
    var formIDs = pdfWriter.createFormXObjectsFromPDF("./test.pdf",
        hummus.ePDFPageBoxMediaBox);    
    cxt.q()
        .cm(1,0,0,1,448,643)
        .doXObject(pdfpage.getResourcesDictionary().addFormXObjectMapping(formIDs[0]))
        .Q()
    pdfWriter.writePage(pdfpage);
    pdfWriter.end();
}
````

supposed to do the same thing. i'll check why...
but in the meantime you can use it instead of drawImage

**Comment by galkahana** [comment]
Reporting back.
I have found the issue causing drawImage to fail in this case, and fixed it.
You should be able to see the correction with 1.0.83 build of hummus.

**Comment by Bastian1975** [comment]
Thanks, working great now
