### ISSUE TITLE
Cannot add both text and image to existing PDF at the same time

### ISSUE THREAD

**Issue by leewei05** [galkahana/HummusJS#210]
variable tmp is my input, Here is my code:

                var tmp=req.body.para;
                var pdfWriter = hummus.createWriterToModify('./contract.pdf', {
                    modifiedFilePath: './pdf/' + 'modified_'+tmp.FileName+'.pdf'
                });       
                var pageModifier = new hummus.PDFPageModifier(pdfWriter,0);
                var textOptions = {font:pdfWriter.getFontForFile('./font/' + 'GenYoMinTW-
                Regular.ttf'),size:8,color:0x00};
   
                pageModifier.startContext().getContext().writeText(
                    tmp.mileage_price.toString(),
                    180, 405,
                    textOptions
                );                
                pageModifier.endContext();   
             
                var cxt = pageModifier.startContext().getContext();
                cxt.drawImage(430,340,'./carImage'+tmp.signImage);
                pageModifier.endContext().writePage();                
                pdfWriter.end();

But it keeps console:
  
                TypeError: Unable to end PDF

I can work if I only modify text, but with image I get this error message. 
Please help!

**Comment by galkahana** [comment]
What if you just place the image?

**Comment by leewei05** [comment]
@galkahana What do you mean by place the image?

**Comment by galkahana** [comment]
Do just the image adding part, without the text adding.

**Comment by leewei05** [comment]
@galkahana   I found the error, I misspelled my path to the image.
Thank you though for the great function !
