### ISSUE TITLE
Getting page dimensions

### ISSUE THREAD

**Issue by Protoneer** [galkahana/HummusJS#212]
Is there a way to determine the page dimensions? (used with **pageModifier.startContext().getContext().writeText("text",X,Y,TextOptions)** )

I need to add at each corner of the page, but I can't find a way to get the max page dimensions.  

Unfortunately all of the PDF's I am adding the timestamp to are different sizes page sizes.

Thanks for the good work, by the way.

**Comment by chunyenHuang** [comment]
You can get the metadata/dimensions from the page info.
https://github.com/galkahana/HummusJS/issues/209#issuecomment-338521832

**Comment by Protoneer** [comment]
For some reason the pageInfo was empty. 

I made compromise populating the 0,0 corner with the needed text.

**Comment by galkahana** [comment]
hmfff. good solution, thought its unfortunate that you didn't get the size.
normally they should be available via pageInfo.getMediaBox()
