### ISSUE TITLE
Password protection with ownerPassword only

### ISSUE THREAD

**Issue by rcwwilliams** [galkahana/HummusJS#220]
Hi

The feature to password protect a PDF document using recrypt is great - thank you.

Is it possible to recrypt a document so it can be opened without a password, but with the activities specified in the userProtectionFlag being password protected?

Thanks

Kind regards

Robin

**Comment by chunyenHuang** [comment]
You can try to set the `userPassword` to `''`.
And set `password` and `ownerPassword` to the one you want.

It should allow you to open the pdf file without password and require password for editing.

**Comment by rcwwilliams** [comment]
Brilliant - thanks so much John / Chunyen.
