### ISSUE TITLE
Bold or Italic text?

### ISSUE THREAD

**Issue by peter-borgstedt** [galkahana/HummusJS#224]
How do I set bold text? Do I really have to load a BOLD font? I mean most fonts have bold included. How do I render bold or italic text?

And how do I load internal fonts? Do i really need to load a font from a file?

**Comment by chunyenHuang** [comment]
Yes, you will need to load the individual font files for `regular` `bold` `italic` `bold/italic` `oblique`. They are separated in your system too. For example, [Arial](https://www.microsoft.com/typography/fonts/font.aspx?FMID=1707)
