### ISSUE TITLE
add page number of X to new PDF, after pages have been created

### ISSUE THREAD

**Issue by simonaberry** [galkahana/HummusJS#232]
I am generating a new PDF from scratch, using `hummus.createWriter` using an in memory byte array custom stream

The number of pages is dynamic. How would I be able to go back over all pages at the end once I know the total pages, to add a footer like `Page 1 of 10` ?

If I use `hummus.createWriterToModify` it looks like I need to have a new input Stream or save the file to fs ..?  Is there not a way to create it directly from the writer generated by  `hummus.createWriter` ?

**Comment by chunyenHuang** [comment]
Is it possible you just save all pdf information to an object and use hummus to write the pdf at the end? Unless you want to see the progress of generating pdf, or you don't need have to create the pdf before you gather all the information to write.

**Comment by simonaberry** [comment]
why didn't I think of that!  Great idea, thanks

**Comment by istvanpp** [comment]
@chunyenHuang, please can you write a sample code to illustrate how to insert page number on each page like Page 1 of X? Thank you.

**Comment by simonaberry** [comment]
@istvanpp you have two options : 

1. If you are generating all the PDF content from non-pdf source (as per my original question), do a dry run as per @chunyenHuang suggestion :
```
    // pseudo code : 
    // first run
    load source information, set pageYCursor = 0, set numPages = 0
    loop through items to print to pdf, 
        determine how much space each item will take, incrementing pageYCursor 
        if pageYCursor > pageLength => numPages ++, pageYCursor = 0
    next item

    //final pass
    load source information, set pageYCursor = 0, set pageNumber = 0
    initialise hummus pdfWriter
    loop through items to print to pdf, 
        write actual data to PDF, incrementing pageYCursor 
        write footer : pageNumber of numPages
        if pageYCursor > pageLength => pageNumber ++, pageYCursor = 0
    next item
``` 

2. If you have an existing PDF document that you just want to stamp the page numbers on, use something like :  

```
    var copyContext = pdfWriter.createPDFCopyingContext();
    var numPages = copyContext.getSourceDocumentParser().getPagesCount();

  ///etc



```

**Comment by istvanpp** [comment]
@simonaberry  Hello, I have the second option with an existing PDF file. 

My sample code what is need to modify is working, but the page number is inserted on the same place and only on the first page. Probably I am using a wrong method:
```
var pdfInserPageNumber = hummus.createWriterToModify('AppendPagesTest.pdf', {
			modifiedFilePath:'AppendPagesTestModif.pdf'
		});

		var pageModifier = new hummus.PDFPageModifier(pdfInserPageNumber,0);
		var getFont = pdfInserPageNumber.getFontForFile('liberationregular.ttf');
		var textOptions = {font:getFont, size:14, colorspace:'gray', color:'red'};
		var totalPages = hummus.createReader('AppendPagesTest.pdf').getPagesCount();
		console.log ("Total Pages:" + totalPages);
		var pageNumber;
		for (pageNumber = 1; pageNumber <= totalPages; pageNumber++) {

			pageModifier.startContext().getContext().writeText('Page ' + String(pageNumber) + 'of ' + String(totalPages), 75, 805, textOptions);
		}
		pageModifier.endContext().writePage();
pdfInserPageNumber.end();
```

**Comment by istvanpp** [comment]
Thank you, this works, but I am not sure if is a good choice to initialize a new pageModifier each time.

like this:
```
for (pageNumber = 1; pageNumber <= totalPages; pageNumber++) {
	pageModifier = new hummus.PDFPageModifier(pdfInserPageNumber, pageNumber-1);
	pageModifier.startContext().getContext().writeText('Page ' + String(pageNumber) + 'of ' + String(totalPages), 75, 805, textOptions);
	pageModifier.endContext().writePage();
}
```
