### ISSUE TITLE
Document properties "Keywords"

### ISSUE THREAD

**Issue by matex1024** [galkahana/HummusJS#256]
First of all, very good job, it's one of the most detailed library for pdf generation in node js. 
During adding metadata, based on your test file/SettingInfoValuesTest.js,
 I tried to add Keywords to my pdf. 
The problem is the keywords are converted to single string and it doesn't matter If I define it as
 `newInfo.keywords = ['keyword1','keyword2','keyword3']` 
or that 
`newInfo.keywords = keyword1+','+keyword2+','+keyword3`.
Based on PDF Keywords in properties, the output should looks like 
`keyword1,keyword2,keyword3`
 instead of
 `"keyword1,keyword2,keyword3"` 
I didn't look too much in C++ lib but I think its quite simple change, I just don't know in which cpp file it's stored. I hope it will help, thank you for help or maybe I'm doing something wrong :).

**Comment by chunyenHuang** [comment]
https://github.com/galkahana/HummusJS/blob/02730266893d288ac6a88148c8f624c41519236e/src/deps/PDFWriter/InfoDictionary.cpp#L68

**Comment by matex1024** [comment]
Thank you make sense now.
