### ISSUE TITLE
Pre-built binaries for Windows and Electron 2.0.2

### ISSUE THREAD

**Issue by simone** [galkahana/HummusJS#294]
Hi,
first of all thank for your library, it's veri useful. I would ask you to upload on S3 the prebuilt for windows of electron 2.0.2.

I'm reading you can use AppVeyor or Travis to make the task in CI.

Let me know if you need help

**Comment by hhaidar** [comment]
I've added builds for electron 1.8 and 2  in #313.

@galkahana please let me know if there's anything else I should do.

**Comment by galkahana** [comment]
ok. so we got electron now.
windows is still a TODO

**Comment by hhaidar** [comment]
via #316, thanks again @galkahana

**Comment by galkahana** [comment]
@hhaidar thank you for your PR :)

ok, we should have windows now too.

**Comment by simone** [comment]
Cool, works perfectly with electron-builder also from my mac osx. Many thanks.
$ npm run build:prod && npx electron-builder build --windows
  • electron-builder version=20.28.2
  • loaded configuration file=app/electron-builder.json
  • writing effective config file=app-builds/builder-effective-config.yaml
  • rebuilding native production dependencies platform=win32 arch=x64
  • packaging       platform=win32 arch=x64 electron=2.0.7 appOutDir=app-builds/win-unpacked
  • building        target=portable file=app-builds/app.exe archs=x64


deps:
"hummus": "1.0.90",

devDeps:
"electron": "2.0.7",
"electron-builder": "20.28.2",

**Comment by hhaidar** [comment]
@simone are you having any issues getting electron-builder to download the correct binaries for cross-platform builds? For example, building for Linux on OSX?

**Comment by simone** [comment]
Let me check...
No, the Linux build don' seem to work from OSX.
