### ISSUE TITLE
Embed multiple PDFs into an already existing PDF

### ISSUE THREAD

**Issue by AlexanderGalen** [galkahana/HummusJS#30]
I can see how to embed multiple PDFs into a new document, using `pdfWriter.mergePDFPagesToPage()`, but I'm having trouble figuring it out when I want to do the same thing, but to an already existing page.

The page parameter used in `pdfWriter.mergePDFPagesToPage()` in all of your examples was obtained by calling `var page = pdfWriter.createPage(0,0,595,842);` or similar, but I don't want to create a new page, and I'm not sure how to get the correct value to pass as the page parameter to `pdfWriter.mergePDFPagesToPage()`

**Comment by angularturk** [comment]
Hello @galkahana thanks for great plugin. Here is a working sample for this issue.

```js
var pdfWriter = hummus.createWriterToModify(
	    new hummus.PDFRStreamForFile('./public/images/template.pdf'),
	    new hummus.PDFStreamForResponse(res)
	);
	
	var pageModifier = new hummus.PDFPageModifier(pdfWriter,0);
		pageModifier.startContext().getContext().writeText(
			'Hello World',
			29, 149,
			{font:pdfWriter.getFontForFile('./public/fonts/arial.ttf'),size:7,colorspace:'rgb',color:0x565859}
		);
		
        pageModifier.startContext().getContext().drawImage(29.4,28.3,'./public/images/logo.pdf');
        pageModifier.endContext().writePage();
        pdfWriter.end();
```
