### ISSUE TITLE
Support Node.js 10 (node-v64 ABI) with pre-built binaries

### ISSUE THREAD

**Issue by RoyHP** [galkahana/HummusJS#302]
Hey Galkahana and co,

I'm curious if you're working on supporting the node-v64 ABI, currently it looks like compiling works on node 10 albeit with a bunch of deprecation warnings.

```
node-pre-gyp WARN Tried to download(404): https://hummus.s3-us-west-2.amazonaws.com/hummus/v1.0.87/node-v64-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for hummus@1.0.87 and node@10.6.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
```

**Comment by galkahana** [comment]
done

**Comment by SquareHatLtd** [comment]
Still issues for me, and can't see what 'done' is referring to. Any chance of instructions?

I have attached the full error file for further info.

This is the error I am getting:
[2018-08-20T08_58_28_197Z-debug.log](https://github.com/galkahana/HummusJS/files/2301824/2018-08-20T08_58_28_197Z-debug.log)


82 verbose stack Error: hummus@1.0.0 install: `node-gyp rebuild`
82 verbose stack Exit status 1
82 verbose stack     at EventEmitter.<anonymous> (C:\Users\stephen.smith\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
82 verbose stack     at emitTwo (events.js:126:13)
82 verbose stack     at EventEmitter.emit (events.js:214:7)
82 verbose stack     at ChildProcess.<anonymous> (C:\Users\stephen.smith\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
82 verbose stack     at emitTwo (events.js:126:13)
82 verbose stack     at ChildProcess.emit (events.js:214:7)
82 verbose stack     at maybeClose (internal/child_process.js:925:16)
82 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
83 verbose pkgid hummus@1.0.0
84 verbose cwd C:\Users\stephen.smith\source\repos\AutoSplit\AutoSplit
85 verbose Windows_NT 10.0.17134
86 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\stephen.smith\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "hummus" "--save"
87 verbose node v8.11.2
88 verbose npm  v6.1.0
89 error code ELIFECYCLE
90 error errno 1
91 error hummus@1.0.0 install: `node-gyp rebuild`
91 error Exit status 1
92 error Failed at the hummus@1.0.0 install script.
92 error This is probably not a problem with npm. There is likely additional logging output above.
93 verbose exit [ 1, true ]

**Comment by galkahana** [comment]
oh that's a windows thing.
node 10 prebuilt binaries is supported on mac/linux, which is what started this issue.
you need windows binaries, which is something i havent dealt with yet.
#294

**Comment by galkahana** [comment]
ok node 10 in win should have binaries now
