### ISSUE TITLE
Extracting page from PDF does not copy original annotations

### ISSUE THREAD

**Issue by MikeBailleul** [galkahana/HummusJS#307]
I'm trying to extract one page from a PDF by doing:

```
const pdfWriter = hummus.createWriter(extractedPdfPath);
pdfWriter.appendPDFPagesFromPDF(sourcePdfPath, {
    type: hummus.eRangeTypeSpecific,
    specificRanges: [[pageIndex, pageIndex]],
});
pdfWriter.end();
```

It works pretty well except for the annotations which are not copied from the original to the new generated PDF.

Here is an example of PDF with annotations that does not work:
[A5.pdf](https://github.com/galkahana/HummusJS/files/2269123/A5.pdf)

**Comment by galkahana** [comment]
copies only graphics natively.
here's how to also copy annotations:
https://github.com/galkahana/HummusJSSamples/tree/master/appending-pages-with-comments

**Comment by MikeBailleul** [comment]
That is awesome, thanks!
