### ISSUE TITLE
Hummus methods are actually not sync (or I messed up something?)

### ISSUE THREAD

**Issue by jacob87o2** [galkahana/HummusJS#314]
Hello,

There are some statements about hummus methods being sync, there #252 and there #164. 

Unfortunately, that's not really true.

We're using node.js v8.11.3, hummus v1.0.86 and we use it like this:
```javascript
const pagesCount = hummus.createReader(inputFilePath).getPagesCount();
const inStream = new hummus.PDFRStreamForFile(inputFilePath);
const outStream = new hummus.PDFWStreamForFile(outputFilePath);
const pdfWriter = hummus.createWriterToModify(inStream, outStream);

// ... some code

pdfWriter.end();
outStream.close();
inStream.close();

// immediately after executing hummus code
fs.stat(outputFilePath, (err, stats) => {
    console.log(stats.size); // prints out 0
});

// after some time (10s for example)
setTimeout(() => {
    fs.stat(outputFilePath, (err, stats) => {
        console.log(stats.size); // prints out actual size - 2789816
    });
}, 10000);
``` 

How can we know when the file is actually ready?

**Comment by galkahana** [comment]
I'll explain.  
When using hummus writer with a file path, then internally hummus uses plain old C++ writing, which is sync (this is both for writing new pdfs and modification of existing pdfs). This is also true for any reading that it does (say from an image or whatnot).

however, when `hummus. PDFWStreamForFile `, in particular, then the writing is using node async IO. PDFWStreamForFile comes with a useful `.close(cb)` method which you can provide a callback to when writing is done. Alternatively you can implement another custom stream implementation that writes sync.

Gal.

**Comment by jacob87o2** [comment]
Thanks for the answer. I converted the callback method to a promise like this: 
```javascript
new Promise(resolve => outStream.close(() => resolve()));
```
... and seems that worked.
