### ISSUE TITLE
Segmentation Fault while Creating Buffers in Dockerized App

### ISSUE THREAD

**Issue by tjohnsonfs** [galkahana/HummusJS#320]
Hello,
Based on [#125](https://github.com/galkahana/HummusJS/issues/125), we have the following code that creates a single pdf from multiple pdfs. Running locally or deployed to Heroku, this code works as expected.

We have Docker containers built on Alpine linux that run this code and give a Segmentation Fault on the line that reads `pdfWriter.appendPDFPagesFromPDF(pdfStream)`. I have also built the same container on a base of the `node:8` Dockerfile, and it seems to work as expected.

- Any ideas on why this would be happening in a Docker container but not other environments? 
- Does the `appendPDFPagesFromPDF` use  the file system under the hood?
- Are there any required C++ libraries/frameworks that a Mac/Some linux distros would have but not simple ones?
- Any idea how we could go about debugging this?

Any help is appreciated!
```
const hummus = require('hummus')
const streams = require('memory-streams')

function pdfmerge (pdfBuffers) {
  return new Promise((resolve, reject) => {
    const writer = new streams.WritableStream()
    const pdfWriter = hummus.createWriter(new hummus.PDFStreamForResponse(writer))

    pdfBuffers.map(data => {
      const pdfStream = new hummus.PDFRStreamForBuffer(data)
      pdfWriter.appendPDFPagesFromPDF(pdfStream)
    })

    pdfWriter.end()

    return resolve(writer.toBuffer())
  })
}

module.exports = pdfmerge
```

**Comment by galkahana** [comment]
i'd start with assuming that the install is fine, and check the input data.
try dumping the buffers to a file and then work with the file. if doesn't work...send yourself the file an open it in a viewer...to see that this is a valid PDF.
If it's ok with a file...time to check `PDFRStreamForBuffer`.

etc.

**Comment by tjohnsonfs** [comment]
Thanks for the response!

We were able to solve this problem by including make, gcc, g++, and python in our Alpine container and running `npm rebuild hummus --build-from-source`.
