### ISSUE TITLE
drawImage()  the image will be blocked if the param is large

### ISSUE THREAD

**Issue by soeyi** [galkahana/HummusJS#322]
### Description
 I tried to modify an existing pdf from buffer.
With my code below, i can get another pdf file `./result.pdf`  just the same as origin one.

```javascript
  //  this is buffer like <Buffer 25 50 44 46 2d 31 ... 6d 29 0a 2f 50 72 6f 64 ... > 
  const buffer = _file.buffer;
  // const readStream = fs.createReadStream(buffer);
  const inStream = new hummus.PDFRStreamForBuffer(buffer);
  const outStream = new hummus.PDFWStreamForFile('./result.pdf');
  const pdfWriter = hummus.createWriterToModify(inStream, outStream);

  let pageModifier = new hummus.PDFPageModifier(pdfWriter, 0, true);
  pageModifier.startContext().getContext().writeText(
    'Test Text2222222',
    300, 500,
    { font: '/Library/Fonts/Arial.ttf', size: 18, colorspace: 'gray', color: 0x00 }
  );
  pageModifier.endContext().writePage();
  pdfWriter.end();
  // inStream.close(() => {
  //   console.log('inStream done');
  // });
  // outStream.close();
```

**Comment by soeyi** [comment]
![image](https://user-images.githubusercontent.com/38489160/45199864-8cb53f00-b2a0-11e8-9756-999caef0a35f.png)

**Comment by chunyenHuang** [comment]
https://github.com/galkahana/HummusJS/wiki/Show-images#simple-image-drawing

maybe you can try with the object instead
```javascript
{
  transformation: {
    width:100,
    height:100,
    proportional:true
  }
}
```

**Comment by soeyi** [comment]
@chunyenHuang 
Thanks~
I tried with the object instead, it still doesnt work.
However, i tried to clone your `hummusRecipe`  and do some change.
To support `new HummusRecipe(buffer)`  receive buffer;
And the result return is also  buffer. Below is usage.
Wondering if i could create a pr to ur repo.
``` javascript
  const pdfDoc = new HummusRecipe(buffer);
  const result = pdfDoc
    .editPage(5)
    .image('./png/google.png', 100, 230, {
      width: 100,
      keepAspectRatio: true,
      opacity: 0.7
    })
    .endPage()
    .endPDF();
```

**Comment by chunyenHuang** [comment]
PR is welcome, but I think your issue should be able to be resolved by the HummusJS. My repo is just a wrapper on top of HummusJS.
