### ISSUE TITLE
Merge append files keeping HTML url links

### ISSUE THREAD

**Issue by lanceschi** [galkahana/HummusJS#329]
Hi,

i followed #181 in order to merge/append multiple PDF files.

It works. It keeps the formatting but the hyper-links got lost in the final output PDF file.

Is it possible to keep/preserve the hyper-links during the merging process?

Any help appreciated. Thanks!

**Comment by galkahana** [comment]
use the onPageWriter event to add annotations (implementation of hyper-links). here's an example:
https://github.com/galkahana/HummusJSSamples/tree/master/appending-pages-with-comments

**Comment by lanceschi** [comment]
@galkahana thanks! It did the trick
