### ISSUE TITLE
Module breaks in v0.12.0 of node

### ISSUE THREAD

**Issue by AlexanderGalen** [galkahana/HummusJS#34]
I updated my node the other day to find that any of my scripts that used hummus worked. The error I get is this: 
```
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Volumes/RESOURCE/node_modules/hummus/hummus.js:2:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

I thought it might have been a problem with node itself, so I opened an issue at https://github.com/joyent/node/issues/9252, and they told me the module is probably not compatible with v0.12.0 or v8.

It may or may not be helpful to note that even trying to install hummus with `npm install hummus` fails with these errors after a bunch of successful messages:
```
1218 error Darwin 12.6.0
1219 error argv "node" "/usr/local/bin/npm" "install" "hummus"
1220 error node v0.12.0
1221 error npm  v2.5.1
1222 error code ELIFECYCLE
1223 error hummus@1.0.38 install: `node-gyp rebuild`
1223 error Exit status 1
1224 error Failed at the hummus@1.0.38 install script 'node-gyp rebuild'.
1224 error This is most likely a problem with the hummus package,
1224 error not with npm itself.
1224 error Tell the author that this fails on your system:
1224 error     node-gyp rebuild
1224 error You can get their info via:
1224 error     npm owner ls hummus
1224 error There is likely additional logging output above.
```
So I'm guessing there's a problem with node-gyp somehow. A lot of this stuff is over my head though, so I'm not sure. I'm just using v0.10.36 of node for now, as that still works fine.

**Comment by galkahana** [comment]
I was able to recreate. i will look into it soon. with v.0.12 there was an upgrade in v8. must have been a very not careful upgrade as it broke builds (turns out my module is not the only one with issues).
i'll figure out the issues, correct, and release a new version. 
Thanks for letting me know.
Gal.

**Comment by galkahana** [comment]
Hi Alexander,
I published an update to hummus that should work well on both versions.

Regards,
Gal.

**Comment by AlexanderGalen** [comment]
Awesome, everything seems to be working fine for me. Thanks for the help. I'll close this issue.
