### ISSUE TITLE
Extract jpg from pdf

### ISSUE THREAD

**Issue by msageryd** [galkahana/HummusJS#341]
Is it possible to extract jpg files from pdfs with Hummus?

**Comment by galkahana** [comment]
You could extract image data from a PDF file. however images are embedded in PDF as raw data encrypted with one or more filter (most of the time it is raw data encrypted with something. like a DCT filter...which is actually JPG). so you'll need to run through the pages, grab their resources dictionaries, grab the images from there, read their streams and export.

yeah possible...there's a bit to learn.
Gal.

**Comment by msageryd** [comment]
Thank you.
I think I'll go ahead with poppler and pdftocairo for extracting images.
