### ISSUE TITLE
Insert page number on each page

### ISSUE THREAD

**Issue by istvanpp** [galkahana/HummusJS#346]
Hi, could you please provide me an example how to add page numbers in the footer of an existing PDF document? 

Isn't clear for me, which method or solutions is the best and the fastest for this process?

My code is working, but I am not sure if I am using the best solution:

```
var pdfInserPageNumber = hummus.createWriterToModify('AppendPagesTest.pdf', {
			modifiedFilePath:'AppendPagesTestModif.pdf' });
var getFont = pdfInserPageNumber.getFontForFile('liberationregular.ttf');
var textOptions = {font:getFont, size:14, colorspace:'gray', color:'red'};
var totalPages = hummus.createReader('AppendPagesTest.pdf').getPagesCount();

var pageNumber;
for (pageNumber = 1; pageNumber <= totalPages; pageNumber++) {
	var pageModifier = new hummus.PDFPageModifier(pdfInserPageNumber, pageNumber-1);
	pageModifier.startContext().getContext().writeText('Page ' + String(pageNumber) + ' of ' + String(totalPages), 460, 38, textOptions); 
	pageModifier.endContext().writePage();
}
pdfInserPageNumber.end();
```

**Comment by galkahana** [comment]
looks like it couldn't get any better.
i mean, i normally like ++a, and not a++, but who cares :).

oh. one thing. you don't need to create another reader for the pdf file.
when creating a modification writer, it creates internally a parser and provider a handle for you. so you can get pages count with:
```
pdfInserPageNumber.getModifiedFileParser().getPagesCount()
```

this should save you some time.

**Comment by istvanpp** [comment]
Thank you @galkahana , I have updated my code based on your observation.
