### ISSUE TITLE
getImageDimensions() doesn't work with buffer as a stream

### ISSUE THREAD

**Issue by silexboy** [galkahana/HummusJS#354]
Hi. I'm trying to merge PDF and image files from S3 to a single PDF document using `PDFRStreamForBuffer()` and `memory-streams` package for the writer.

            const writer = new streams.WritableStream();
            const pdfWriter = hummus.createWriter(new hummus.PDFStreamForResponse(writer), {
		       compress: false,
		       log: '...'
	        });

		const {Body: data} = await s3.getObject(...).promise();
            ...

		if (type === 'pdf') {
			pdfWriter.appendPDFPagesFromPDF(new hummus.PDFRStreamForBuffer(data)); // OK
		}
		else if (['jpg', 'jpeg', 'png'].includes(type)) {
			const stream = new hummus.PDFRStreamForBuffer(data);
			const dimensions = pdfWriter.getImageDimensions(stream);  // NOT OK
            ...

As you see, the similarly created stream is good because `appendPDFPagesFromPDF()` works good. The problem is that `getImageDimensions()` doesn't work with such stream (and works well with the same image as local file, so the image is also ok).

I would be happy if somebody advice what's wrong here.

**Comment by diegoolavarria** [comment]
@silexboy do you manage to do this task? I have to do exactly the same and I'm stuck with trying to add the images to the final pdf document

**Comment by goatandsheep** [comment]
and `createImageXObjectFromJPG` doesn't accept buffer either

**Comment by goatandsheep** [comment]
I've placed a [bounty](https://www.bountysource.com/issues/67636474-getimagedimensions-doesn-t-work-with-buffer-as-a-stream) on this issue

**Comment by willy2dg** [comment]
@goatandsheep Could be enough by creating a `getStreamImageDimensions` method or allowing `getImageDimensions` to accept a stream ?

**Comment by goatandsheep** [comment]
@willy2dg I do want `createImageXObjectFromJPG` to accept buffer, but the bounty is just for `getImageDimensions` so yes.

**Comment by willy2dg** [comment]
Ok @goatandsheep , I will be checking it . Anyways `createImageXObjectFromJPG` seems to be accepting a stream as input.

**Comment by willy2dg** [comment]
@goatandsheep I sent a PR. The steps to run it are the following :

- Clone repo
- In repo folder, run `npm install --build-from-source`
- In repo folder, run `npm link` ( create npm link to package )
- In your project folder, run `npm link hummus` ( link local package instad of installing from npm )

**Comment by goatandsheep** [comment]
Weird: `npm install --build-from-source` gave me [165 warnings](https://gist.github.com/goatandsheep/601417d691b5dc689a3ee34ac2a88e91)

**Comment by willy2dg** [comment]
I got warning too, but they was there before my changes.

**Comment by willy2dg** [comment]
@galkahana is this able to be merged ?
@goatandsheep can we close the issue ?

**Comment by goatandsheep** [comment]
@willy2dg I want the PR to be merged before we can close the issue. @galkahana I setup a ticket to figure out what to do re Travis issues (see link in PR)

**Comment by goatandsheep** [comment]
Hi @silexboy can we close the issue? The [fork works](https://travis-ci.com/goatandsheep/HummusJS/builds/128554222) and will be merged as soon as @galkahana sees it. @willy2dg deserves the bounty.

**Comment by willy2dg** [comment]
The only activity in the @silexboy account is to open this issue, so I doubt it responds. @galkahana could you close this ?

**Comment by galkahana** [comment]
published as 106
