### ISSUE TITLE
Pre-gyp?

### ISSUE THREAD

**Issue by brianreavis** [galkahana/HummusJS#36]
Thanks for the epic library! Are you open to setting up Travis and [node-pre-gyp](https://github.com/mapbox/node-pre-gyp)? With it in place it'd remove the need to compile the library on most machines. I could lay most of the groundwork if that'd be helpful. I've been using it for [node-gdal](https://github.com/naturalatlas/node-gdal) (whose compile times are much longer) and it's been super helpful.

**Comment by galkahana** [comment]
open, yeah. though i'm not familiar yet with it. will read, looks interesting. in the meantime if you got some time and will to assist, go for it :). thanks. Gal.

**Comment by taxilian** [comment]
this would be moderately awesome =]

**Comment by brianreavis** [comment]
I've set this up here: https://github.com/naturalatlas/HummusJS (prebuilt binaries available for OSX and linux). @galkahana If interested and if you set up Travis / a S3 bucket, I'd be happy to help integrate this back into this repo. Otherwise, I don't mind keeping the fork up to date

**Comment by galkahana** [comment]
thanks @brianreavis. i'll setup a travis account soon as well as s3. might need some help as i'm not very familiar with pregyp.
bare with me though...super busy with other matters, mfraid.

b.t.w, just to clear things - travis is interesting for this matter? or just another thing altogather simply running the tests?

**Comment by brianreavis** [comment]
> travis is interesting for this matter? or just another thing altogather simply running the tests?

Travis is needed in order to build all the different variations. Right now it's configured to build: 0.10, 0.12, 4.0, and 4.2 for both Linux and Mac. If `[publish binary]` is found in the commit message pre-gyp, will package up `hummus.node` and place it on S3 for each build.

**Comment by galkahana** [comment]
@brianreavis seems like all there is to do (after i opened a travis account and created an S3 bucket) is to:
1. grab your .gitignore as is
2. grab your .travis.yml as is (except maybe those funky global secure...what are these?)
3. grab your binding.gyp as is
4. grab your hummus.js as is
5. grab your package.json
  5.1 change the following to fit to the current values in my repo - name, description, repository/url,
  5.2 change binary/host to point to my S3 bucket
[do i need the makefile?]

makes sense?

looks like i'll also need to setup permissions properly on S3. i'll follow the node-pre-gyp instructs.

anything else you can warn me from? i'm a bit clueless here.

Gal.

**Comment by brianreavis** [comment]
> do i need the makefile?

Nope! It's just something I use to save on some typing. Not mandatory.

> grab your .travis.yml as is (except maybe those funky global secure...what are these?)

For the global secure values, see [this section](https://github.com/mapbox/node-pre-gyp#travis-automation) of the pre-gyp guide. Those are just S3 credentials that pre-gyp uses to upload the artifacts. Those are the only values in `.travis.yml` you should have to update.

> anything else you can warn me from?

When setting up the bucket policy ([guide](https://github.com/mapbox/node-pre-gyp#1-create-an-s3-bucket)), make sure the `"Resource"` array looks like this:
```
"arn:aws:s3:::galkahana-node-binaries",
"arn:aws:s3:::galkahana-node-binaries/*"
```
Instead of this:
```
"arn:aws:s3:::galkahana-node-binaries/*"
```
The guide only lists the second one, which caused problems for me. Other than that, I think that's about it. If there's anything specific that pops up, drop a comment here and I'll try to help figure it out.

**Comment by brianreavis** [comment]
@galkahana Awesome – looks like it's all set up!
```sh
Brians-MacBook-Pro:~ brianreavis$ npm install hummus
> hummus@1.0.45 install /Users/brianreavis/node_modules/hummus
> node-pre-gyp install --fallback-to-build

[hummus] Success: "/Users/brianreavis/node_modules/hummus/binding/hummus.node" is installed via remote
hummus@1.0.45 node_modules/hummus
```

**Comment by galkahana** [comment]
yap. @brianreavis  thanks a lot man for all your help on this. wonderful new addition.
