### ISSUE TITLE
It removes some digital signatures

### ISSUE THREAD

**Issue by raminious** [galkahana/HummusJS#363]
I'm using this library to select some pages from the existing file and create a new pdf based on that file.  
I just figured out it removes some digital signatures.  

Main pdf:   
![image](https://user-images.githubusercontent.com/334716/54938192-f7755180-4f36-11e9-9e7b-d2ab31f49af8.png)

Generated pdf:  
![image](https://user-images.githubusercontent.com/334716/54938231-065c0400-4f37-11e9-8fbe-7e4b936aab55.png)

(please see the seller field)

Is there any workaround? I could find nothing in the documents.

**Comment by raminious** [comment]
this is the file

[Revised_Offer_for_912_Brose_Signed_by_McGregors1_ts04828.pdf](https://github.com/galkahana/HummusJS/files/3004977/Revised_Offer_for_912_Brose_Signed_by_McGregors1_ts04828.pdf)

**Comment by raminious** [comment]
I have to replace this tool with something else.

**Comment by raminious** [comment]
Ok, now I'm using `qpdf` and my problem is resolved.

**Comment by leungster** [comment]
I was having a similar issue and noticed annotations don't get copied when appending pages. This [sample](https://github.com/galkahana/HummusJSSamples/blob/master/appending-pages-with-comments/appendWithComments.js) handles the use case.
