### ISSUE TITLE
CMYK Colors + Illustrator edit function

### ISSUE THREAD

**Issue by steffenmllr** [galkahana/HummusJS#38]
Hey there, first of thank for the library!

I'm trying to add a Text an [existing pdf](http://cl.ly/azl5) in `CMYK (C:83 M:33 Y:74 K:17)` - which is the same color as the ring in the existing pdf. When I try to add a text it somehow doesn't get the color right Here is the [output](http://cl.ly/azXI)

Any ideas why that? Also another question? Why isn't the text visible when I open the file in Illustrator (osx, CS6) while in acrobat reader it shows up?

```js
var hummus = require('hummus');
var pdfWriter = hummus.createWriterToModify('./input.pdf',{modifiedFilePath:'./output.pdf'});
var pageModifier = new hummus.PDFPageModifier(pdfWriter,0);

pageModifier.startContext().getContext()
    .writeText('Test Text', 10, 10, {
        font: pdfWriter.getFontForFile('./tradegothicltstdbd2.ttf'),
        size: 12,
        colorspace: 'cmyk',
        color: 0x83337417 // C:83 M:33 Y:74 K:17
    });

pageModifier.endContext().writePage();
pdfWriter.end();
```

**Comment by galkahana** [comment]
The CMYK values seems to be in percentage going from 1 to 100.The values that the method expects are from 0..255 encoded to hex.To get what you want take each value, multiply by 255 and divide by 100. take the integer part and convert to hex.Then it should work OK.
As for illustrator, i do not know. maybe illustrator cannot render pdf text. I think the problem may be with illustrator, and not with the pdf.
Gal.
Date: Sun, 17 May 2015 13:44:43 -0700

**Comment by steffenmllr** [comment]
Great, thanks for your help, I kind of got `0xD354BC2B` which seems like it is the same color. For the illustrator stuff: I figured out it depends on the input format. I switched to `PDF/X-3` format. Now a can't edit the text (doesn't recognize the font) but it gets displayed.


Btw. it would really be great if the CMYK / RGB color would just except the 0-100 and 0-255 values and not not the hex values - or (since nobody likes breaking change): add a color and color conversion tool something like `hummus.color('cmyk', '83337417')` which converts to the right color in hex. Or you could just add a article to the wiki about how colors work :)

Thanks again

**Comment by galkahana** [comment]
i'll start with a better explanation in the wiki area, then later when i have more mindspace ill add something. thanks.
