### ISSUE TITLE
Font characteristics

### ISSUE THREAD

**Issue by martinheidegger** [galkahana/HummusJS#39]
@galkahana I have high respect for your library. One thing makes the use for me problematic though: To arrange text exactly I need to know the font characteristics. getting the font dimensions using `writer.getFontForFile(..).calculateTextDimensions` is a first step but really the other characteristics are very important to align as well, i.e. a text with all small characters like "nano" has different dimensions than one with a "f" or "y" in it: In short The baseline is very important to arrange text carefully. 

![font-characteristics](https://cloud.githubusercontent.com/assets/914122/8029297/4bc74102-0df6-11e5-8c5c-17de250c0cdb.png)

Is there a way to figure that out?

**Comment by galkahana** [comment]
Hi Martin,
The information is available, but there's a bit of work here. One needs to expose it to the javascript code.
The underlying C++ library implementing hummusJS holds a FreeType font instance. FreeType is a very able font library and you can probably use that instance to get the required info.

For example, calculateTextDimensions implementation uses that FreeType instance (here - https://github.com/galkahana/HummusJS/blob/master/src/UsedFontDriver.cpp#L87).

C++ users of the library can just go and get the data.
HummusJS users (well, devs, cause you need to change the module) need to expose it.

You can have a go, if that's interesting to you. I can probably asists if you let me know which properties you need exposed. (this is what the FT_FACE structure holds, but there's more - http://www.freetype.org/freetype2/docs/reference/ft2-base_interface.html#FT_FaceRec).

And obviously one can always read the font file itself and parse it if there's anything freetype doesn't give easily.
