### ISSUE TITLE
Question: what is the latest release that is compatible with ABI version 57?

### ISSUE THREAD

**Issue by jeanpchr** [galkahana/HummusJS#397]

**Comment by galkahana** [comment]
As far as i know node8 is still supported and has ptebuilt binaries

**Comment by jeanpchr** [comment]
You are correct @galkahana, I've tested it locally using node8 and had no issues.

I've tried running my app as an "Azure Function" and MS' platform complained about Hummus' bindings had being compiled using "NODE_MODULE_VERSION" 64 and that 57 was required, that's why I've opened this question. There has to be something else about Azure. 

In any case, thanks for the feedback, and thanks a lot for the project, is has been quite useful.
