### ISSUE TITLE
createReader returns empty object

### ISSUE THREAD

**Issue by adriaanwm** [galkahana/HummusJS#41]
When I use hummus.createReader(<filename>) I don't get any errors but the returned object is empty. This is what happens in the node console...

~~~ JavaScript
> var hummus = require('hummus');
> var pdfReader = hummus.createReader('sample.pdf');
> pdfReader 
{}
>
~~~

**Comment by galkahana** [comment]
I think that this only means that it doesnt have enumerable properties. Do you have actual priblems operating it?

**Comment by adriaanwm** [comment]
I'm new to Javascript and never came across that before. Thanks so much for the quick response and for making such an awesome tool!

**Comment by galkahana** [comment]
No worries. Dont ask and youll never know :).
Good luck abd thanks.

**Comment by midthun** [comment]
I am encountering this same issue. When inspecting the object I get from `createReader`, I only get `PDFReader {}` and there are no functions I can use. Tried with several different PDF files. I use Typescript and my code will be transpiled to javascript, can this be the issue?
