### ISSUE TITLE
Build error with newest v1.0.105

### ISSUE THREAD

**Issue by econner** [galkahana/HummusJS#414]
Hello! 
Thanks for the great lib. We started getting this build error on Heroku with the newest version 1.0.105 that appears to have been released just a few hours ago. Not sure what's to blame here, but figured I'd report it.

` make: Entering directory '/tmp/node_modules/hummus/build'
         CXX(target) Release/obj.target/pdfwriter/src/deps/PDFWriter/AbstractContentContext.o
       make: Entering directory '/tmp/node_modules/hummus/build'
         CXX(target) Release/obj.target/pdfwriter/src/deps/PDFWriter/AbstractContentContext.o
         CXX(target) Release/obj.target/pdfwriter/src/deps/PDFWriter/AbstractWrittenFont.o
       sed: can't read ./Release/.deps/Release/obj.target/pdfwriter/src/deps/PDFWriter/AbstractContentContext.o.d.raw: No such file or directory
       src/deps/PDFWriter/pdfwriter.target.mk:247: recipe for target 'Release/obj.target/pdfwriter/src/deps/PDFWriter/AbstractContentContext.o' failed
       make: *** [Release/obj.target/pdfwriter/src/deps/PDFWriter/AbstractContentContext.o] Error 2
       make: Leaving directory '/tmp/node_modules/hummus/build'`

**Comment by galkahana** [comment]
cheers.
sorry for that. can you tell me what version of node you're using there?
also a bit about the compiling env? os etc.?

**Comment by galkahana** [comment]
oh. i see binaries were not published for some environments due to connection timeouts with aws. i'll rerun the build job and hopefully it'll be better then. give it ~hr

**Comment by galkahana** [comment]
another hour. sorry. creds and stuff. very confusing.

**Comment by galkahana** [comment]
electron builds for linux and osx seems to not be able to create binaries properly. ill look at it later. the rest should be fine now.

**Comment by galkahana** [comment]
k electron looks good too.

**Comment by econner** [comment]
thanks can confirm that it builds for me now too!

**Comment by ebdrup** [comment]
@galkahana 
Thank you so much for this GREAT module! 
I just wanted to let you know that I have this error appearing on Heroku now when trying to install Hummus 1.0.108. Was there a problem publishing the binaries again? Or is it something else?
