### ISSUE TITLE
PDFParser::StartPDFParsing returns failure for some PDFs

### ISSUE THREAD

**Issue by hadasg** [galkahana/HummusJS#42]
Hi,
For some PDFs PDFParser::StartPDFParsing returns failure. After an investigation I found out that the problem caused when parsing the Trailer dictionary, the failure prints to the log is: TRACE_LOG("PDFParser::ParseTrailerDictionary, failure to parse trailer dictionary");

In order to reproduce this issue you only need to execute the following lines.

InputFile pdfFile;
pdfFile.OpenFile(m_FilePath);

PDFParser pdfParser;
if (pdfParser.StartPDFParsing(pdfFile.GetInputStream()) == PDFHummus::eFailure)
		return false;

**Comment by galkahana** [comment]
Thanks.
can you please send me an example PDF, for one that fails?
should be easier then to figure out what the parser don't like about this. 

Regards,
Gal.

**Comment by hadasg** [comment]
Of course, but since it is impossible to attach PDF files via GitHub I'll send you by email.

Thanks,
Hadas

**Comment by galkahana** [comment]
k. thing is that in this PDF the trailer looks like this:

    trailer<</Size 1531/ID[<25c5abd7abe24a0d7da6c2f0aeddc947><cef22872321e5b8f01cff81d02873a90>]>>

keyword being adjacent to the dictionary (instead of say, in the next line) confuses the parser. 
corrected, you can check out the latest commit for the changes.

thanks,
Gal.

**Comment by hadasg** [comment]
Hi Gal,

Thank you for the quick fix.
PDFParser::ParseTrailerDictionary works good now, but PDFParser::StartPDFParsing still returns failure. This time the parsing of the dictionary has failed.
The failure prints to the log is: 
TRACE_LOG("PDFParser::ParseDirectory, failure to parse trailer dictionary");

Thanks,
Hadas

**Comment by galkahana** [comment]
crap.
sorry.
will look into it sometime.

**Comment by hadasg** [comment]
Thanks a lot.

**Comment by galkahana** [comment]
Hadas,
comitted another small change. check the last commit of pdfwriter.
should correct the next problem. this time i also verified that parsing finishes, and i get the right number of pages (as indication for proper parsing).

Gal.

**Comment by hadasg** [comment]
It works perfectly now.
Thank you.

Hadas.
