### ISSUE TITLE
missing prebuilt binaries for windows and node 12.x

### ISSUE THREAD

**Issue by abenhamdine** [galkahana/HummusJS#423]
Hi and thx for this great module.  
I run into this error when I `npm install` on Windows with nodejs 12.8.1 (it worked perfectly with nodejs 10.15.0) :  

```
> hummus@1.0.105 install C:\projects\payroll-app\node_modules\hummus
> node-pre-gyp install --fallback-to-build $EXTRA_NODE_PRE_GYP_FLAGS

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://hummus.s3-us-west-2.amazonaws.com/hummus/v1.0.105/node-v72-win32-x64-unknown.tar.gz
node-pre-gyp WARN Pre-built binaries not found for hummus@1.0.105 and node@12.8.1 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Pre-built binaries not installable for hummus@1.0.105 and node@12.8.1 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error Connection closed while downloading tarball file

```
IIUC there are now prebuilt binaries for Windows with that commit https://github.com/galkahana/HummusJS/commit/75522cedc45ffe759f22f1a143297556cf1d60a6, but are they published ?

**Comment by rbeeger** [comment]
node 12 is missing in the appveyor build matrix. I added it in my electron 6 pre-builts PR https://github.com/galkahana/HummusJS/pull/421 .

**Comment by abenhamdine** [comment]
> 
> 
> node 12 is missing in the appveyor build matrix. I added it in my electron 6 pre-builts PR #421 .

ok, thx for your answer and the for the PR !

**Comment by galkahana** [comment]
k. sorry for taking the time...was saving the world n' stuff.
anyways, merged & rebuilt so you should have the new binaries available now.

**Comment by rbeeger** [comment]
@galkahana Thanks for this and also generally for providing Hummus as an open source module.

**Comment by abenhamdine** [comment]
@galkahana thx a lot 💃 💃

**Comment by abenhamdine** [comment]
I close, no pb for installing node 12 prebuitlt binaries now.
