### ISSUE TITLE
Node 4.0+ (Convert to NAN)

### ISSUE THREAD

**Issue by brianreavis** [galkahana/HummusJS#50]
Currently HummusJS doesn't compile on anything above 0.12, despite #44. See https://travis-ci.org/naturalatlas/HummusJS. This is likely a pretty decent-sized job, but it'd probably be worthwhile to drop [nodes.h](https://github.com/galkahana/HummusJS/blob/master/src/nodes.h) in favor of [NAN](https://github.com/nodejs/nan).

Refs #44

**Comment by galkahana** [comment]
Let me think about it. maybe it doesn't have to be that hard. after all nodes.h is just doing what NAN does.
might take me a while but i'll try to get to this.

b.t.w thanks for the travis work.

Gal.

**Comment by brianreavis** [comment]
Actually, my bad – the build errors just had to do with the compiler version I was using. It's looking good for 4.0 and 4.2.
