### ISSUE TITLE
NEW! "unable to append page, make sure it's fine"

### ISSUE THREAD

**Issue by unimaginativeGitHub** [galkahana/HummusJS#52]
Hi galkahana,

First off, thanks SOOO much for all you've built with HummusJS, it's great!

And to the issue I'm having, I've been using Hummus for a couple weeks now and it's working great!  But this morning I grabbed a 'test-pdf' [www.orimi.com/pdf-test.pdf] (www.orimi.com/pdf-test.pdf) and tried to merge it with another document that I know has been clean/worked in the past, and I got this error:

`"unable to append page, make sure it's fine"`

Here's a snippet of the code I'm using (note, I'm using underscore):

```
var pdfWriter = hummus.createWriter(outputPDFFilePath);

_.each(arrayOfFilePathsToAppend , function(nextFileToAppend) {
      pdfWriter.appendPDFPagesFromPDF(nextFileToAppend);
})

pdfWriter.end();
```

I don't usually have control over the pdfs that I need to append... Is there some way this can be fixed or that I can 'help' hummusJS by using a different method or providing more information?

Thanks so much for your help and for all you've done!

**Comment by unimaginativeGitHub** [comment]
Quick update, it looks like the source of the error may be due to the file being password protected for editing purposes...  Is there any way to have hummus work around the password?  Or remove it?

**Comment by galkahana** [comment]
nope. one thing that i never got to doing was supporting either addition or removal of encryption. it's a limitation. you'll have to use some other tool to decrypt the PDF, and later encrypt it again

**Comment by unimaginativeGitHub** [comment]
Thanks for your quick response galkahana.

I was able to find a GhostScript method that allows you to copy a pdf and remove it's security in the process:  

http://www.commandlinefu.com/commands/view/4345/remove-security-limitations-from-pdf-documents-using-ghostscript

Thanks again!
