### ISSUE TITLE
Check if PDF is password protected before editing

### ISSUE THREAD

**Issue by frikkievb** [galkahana/HummusJS#53]
Hi

I am not sure how to achieve this.  I need to check if a PDF is not password protected before trying to modify it.  How can I achieve this with HummusJS?

Thank you.

**Comment by galkahana** [comment]
look at:
https://github.com/galkahana/HummusJS/wiki/Parsing

you can create a parser object on the PDF file and then ask isEncrypted.

Note that hummus cannot modify encrypted files (or parse much of them).
never got to implementing encryption/decryption.

Regards,
Gal.

**Comment by frikkievb** [comment]
Hi Gal

Thanks for the feedback.  The parser seems to pick up on the encryption, but I am not sure how I close the file reader?  I tried using reader.end() and reader.close()  but none seem to be working.  Can't find it in the docs.  

If you would be so kind as to assist.

Thank you for the help.  It's much appreciated.

**Comment by frikkievb** [comment]
Looks like I got it working by using this:

var pdfReader = pdfWriter.getModifiedFileParser();

Thank anyway for sending me in the right direction. :)
