### ISSUE TITLE
Adding a CropBox

### ISSUE THREAD

**Issue by unimaginativeGitHub** [galkahana/HummusJS#54]
I'm building a pdf with the same MediaBox as "pdfFilePath.pdf" but I'd also like to be able to add the same CropBox.  How do I go about adding a CropBox to my 'page'?

```Javascript
var pdfWriter = hummus.createWriter("outputPath.pdf");
var pdfReader = hummus.createReader("pdfFilePath.pdf");

_.times(numberOfPages, function(it) {
     var mediaBox = pdfReader.parsePage(it).getMediaBox();
     var cropBox = pdfReader.parsePage(it).getCropBox();
     var page = pdfWriter.createPage(mediaBox[0],mediaBox[1],mediaBox[2],mediaBox[3]);
     .....
     pdfWriter.writePage(page);
}

pdfWriter.end();
```

Thanks!

**Comment by galkahana** [comment]
Hi,
No current method to set cropbox, artbox etc.

The underlying C++ library allows it through the page object, so it can be easily added to the JS module. is that interesting for you?

**Comment by unimaginativeGitHub** [comment]
It would be nice to be able to set CropBox and MediaBox when creating a new page.

In the mean time I was able to get a workaround to do what I needed.

The vast majority of PDFs do tend to just employ a MediaBox, in your experience, do you think others would find the MediaBox AND CropBox setting ability useful?

**Comment by galkahana** [comment]
donnow.
tell you what. i had to publish a new build of hummus for some other capability i needed.
So i added the ability to set ArtBox, CropBox, BleedBox and TrimBox.

after creating a page just set artBox, cropBox, bleedBox or trimBox on the page variable.
see here an example:
https://github.com/galkahana/HummusJS/blob/master/tests/PageBoxes.js

**Comment by unimaginativeGitHub** [comment]
Awesome!

Thanks again for all the work you've done to make HummusJS!
