### ISSUE TITLE
Parsing: cannot decode name of field. Characters garbled (question marks)

### ISSUE THREAD

**Issue by fedyunin** [galkahana/HummusJS#55]
Hi!
I asked about this issue in other thread here. But I decided renew it and created a new issue for pay more attention for it here.

When I parse PDF receive name of field with incorrectly decoded value (may be wrong charset): e.g: ��. PDF file contains only english text. Why this happens? Should I check charset of PDF file or something other? How to decode such string?

Thanks!

**Comment by galkahana** [comment]
it's problem a PDF text string. This is encoded using a special pdf encoding. 
try  using .toText() on the field name object, like in https://github.com/galkahana/HummusJS/blob/master/tests/ParseInfo.js#L13

**Comment by fedyunin** [comment]
It helped me to solve this issue. Thanks a lot!

**Comment by galkahana** [comment]
cool
