### ISSUE TITLE
Page Rotation

### ISSUE THREAD

**Issue by unimaginativeGitHub** [galkahana/HummusJS#59]
Hi Gal,

I'm currently using your HummusJS to combine and crop many pdf documents into one.  My current setup looks like this:

```javascript
  var pdfWriter = hummus.createWriter(outputPDF);

  _.each(arrayOfFilesToAppend, function(nextDoc) {

    var pdfReader = hummus.createReader(nextDoc);

    var numberOfPages = pdfReader.getPagesCount();

    _.times(numberOfPages, function(it) {
      var cropBox = pdfReader.parsePage(it).getCropBox();

      var page = pdfWriter.createPage(cropBox[0],cropBox[1],cropBox[2],cropBox[3]);

      var contentContext = pdfWriter.startPageContentContext(page);

      pdfWriter.mergePDFPagesToPage(page,
        nextDoc,
        {type: hummus.eRangeTypeSpecific,specificRanges:[[it,it]]});

      pdfWriter.writePage(page);
    });
  });

  pdfWriter.end();
```

I'd like to take the existing page rotation into account when merging these pdfs.  Is there a way for me to read in and set the page rotation in a similar fashion to how I am pulling in the CropBox?

Thanks for all the work you've done on HummusJS!

- Bradley

**Comment by galkahana** [comment]
Hi,
this is a little embarrassing :)
while both capabilities exist in the C++ PDF library i didn't expose them for hummus JS module.
getting - https://github.com/galkahana/PDF-Writer/blob/master/PDFWriter/PDFPageInput.h#L61
setting - https://github.com/galkahana/PDF-Writer/blob/master/PDFWriter/PDFPage.h#L48

10 mts job to expose them and republish. 5 more with example.
i'll try to find the time today.

Regards,
Gal.

**Comment by unimaginativeGitHub** [comment]
Ah, I was wondering about that.  I was going through the C++ PDF Library and I came across the rotation methods.

Thanks so much for looking into that!

- Bradley

**Comment by galkahana** [comment]
k. ready.
with new version (1.47) you can go:

    page.rotate =  pdfReader.parsePage(it).getRotate()

**Comment by unimaginativeGitHub** [comment]
Awesome!

I'll give that a try!

Thanks so much!

**Comment by deftflux** [comment]
I'm trying to do something similar--take an existing PDF and rotate one of its pages.  I've been looking through documentation and source code for a while, but I'm still not sure how to do it.  I see the `setRotate` method on PDFPage, but I don't see how to use it when writing or copying a PDF.  Any help would be appreciated!  Thanks.

**Comment by galkahana** [comment]
Two options:

1. Modify the existing file. grab the page object, change its rotation flag. takes some lower level commands as no high level equivalents exits.
2. Create a new PDF file, import the pages. for pages that you want to change the rotation don't copy directly, rather create a new page, set its rotation flag, and *merge* the source page content to it. you can find out info about copying in [here](https://github.com/galkahana/HummusJS/wiki/Embedding-pdf#advanced-pdf-embedding-with-documentcopyingcontext).

I'll show here how to implement the 2nd option, following the same route as a sample [to change page size](https://github.com/galkahana/HummusJS/blob/master/tests/ModifyingExistingFileContent.js#L93):

````javascript
var hummus = require('hummus');

var pageIndexToChange = 0;
var desiredRotation = 90;

var pdfWriter = hummus.createWriterToModify(
 					__dirname + '/original.pdf',
					{
						modifiedFilePath:__dirname + '/result.pdf'
					});

var copyingContext = pdfWriter.createPDFCopyingContextForModifiedFile();
var pageObjectID = copyingContext.getSourceDocumentParser().getPageObjectID(pageIndexToChange);
var pageJSObject = copyingContext.getSourceDocumentParser().parsePage(0).getDictionary().toJSObject();

// create a new version of the page object
var objectsContext = pdfWriter.getObjectsContext();
objectsContext.startModifiedIndirectObject(pageObjectID);
var modifiedPageObject = inPDFWriter.getObjectsContext().startDictionary();

// copy all but Rotate elements
Object.getOwnPropertyNames(thirdPageObject).forEach(function(element,index,array) {
	if (element != 'Rotate') {
		modifiedPageObject.writeKey(element);
		copyingContext.copyDirectObjectAsIs(thirdPageObject[element]);
	}
});

// setup new rotate and finish object
modifiedPageObject.writeKey('Rotate');
objectsContext
	.writeNumber(desiredRotation)
	.endLine()
	.endDictionary(modifiedPageObject)
	.endIndirectObject();

pdfWriter.end();
````

**Comment by deftflux** [comment]
Thanks!  I have rotation working now.  It looks like your example is actually the 1st option of using lower-level functions to modify, which is fine.  I did notice some bugs/typos, though, so in case anyone else sees this and tries to use it, here is some corrected code:

```js
var hummus = require('hummus');

var pageIndexToChange = 0;
var desiredRotation = 90;

var pdfWriter = hummus.createWriterToModify(
                    __dirname + '/original.pdf',
                    {
                        modifiedFilePath:__dirname + '/result.pdf'
                    });

var copyingContext = pdfWriter.createPDFCopyingContextForModifiedFile();
var parser = copyingContext.getSourceDocumentParser();
var pageObjectID = parser.getPageObjectID(pageIndexToChange);
var page = parser.parsePage(pageIndexToChange);
var pageJSObject = page.getDictionary().toJSObject();

// in case the prior rotation is needed to calculate the new rotation, as it was in my case, it's available here:
var oldRotation = page.getRotate();

// create a new version of the page object
var objectsContext = pdfWriter.getObjectsContext();
objectsContext.startModifiedIndirectObject(pageObjectID);
var modifiedPageObject = pdfWriter.getObjectsContext().startDictionary();

// copy all but Rotate elements
Object.getOwnPropertyNames(pageJSObject).forEach(function(element,index,array) {
    if (element != 'Rotate') {
        modifiedPageObject.writeKey(element);
        copyingContext.copyDirectObjectAsIs(pageJSObject[element]);
    }
});

// setup new rotate and finish object
modifiedPageObject.writeKey('Rotate');
objectsContext
    .writeNumber(desiredRotation)
    .endLine()
    .endDictionary(modifiedPageObject)
    .endIndirectObject();

pdfWriter.end();
```

**Comment by Ko-donghyun** [comment]
Hi. I'm trying to use hummusJS.

I want to use hummus like [ModifyExistingPageContent.js](https://github.com/galkahana/HummusJS/blob/149b6bf8a6da3eb309f6002a552c4f5703084eee/tests/ModifyExistingPageContent.js)..

however, in my modifiedPDF file contains standing 'Test Text'..

what am I supposed to do?

` 

    var pdfWriter = hummus.createWriterToModify('InPlaceModified.pdf',
        {
            modifiedFilePath: 'myresult.pdf'
        })

    var pageModifier = new hummus.PDFPageModifier(pdfWriter,0);
    var context = pageModifier.startContext().getContext();

    context.writeText(
        'Test Text',
        20, 20,
        {font:pdfWriter.getFontForFile('THELeft.ttf'),size:14,colorspace:'gray',color:0x00}
    )
    
    pageModifier.endContext().writePage();
    pdfWriter.end();`
[This is originalPDF](https://drive.google.com/file/d/0B2Ez-Flnfr4LV204Y1VSMEo0dzQ/view?usp=sharing)..
[This is outputPDF](https://drive.google.com/file/d/0B2Ez-Flnfr4LVDB6cVRtRWlVS1E/view?usp=sharing)..

Thank you in advance

**Comment by galkahana** [comment]
seems like the page content are rotated.
the simplest way to go about this is to place the following line prior to the `writeText` line:

    context.cm(1,0,0,-1,0,792)

this should rotate the content back, putting the text at proper 20,20.

**Comment by Ko-donghyun** [comment]
Thank you. Very nice.

but, How can I get contents are rotated?

**Comment by galkahana** [comment]
Well, knowing whether content are rotated is a little bit tough, so its better to make sure that they are not.

Rotating, as any other matrix transformation, is achieved by using the cm operator, as used in my earluer comment.

**Comment by Ko-donghyun** [comment]
Umm..  with cm operator, how can I rotate content 90 degree?

**Comment by galkahana** [comment]
yeah...should prbbly explain about that.
cm operator is general purpose for any kind of transformation, 90 degree rotation being one of them.
context.cm(a,b,c,d,e,f) corresponds to a 2 dimensional transformation matrix, with translation, basically
x' = ax + cy + e
y' = bx + dy + f

you can find a general explenation here:
http://wwwimages.adobe.com/content/dam/Adobe/en/devnet/pdf/pdfs/PDF32000_2008.pdf#page=122

for the general rotation case you'll need to call `context.cm(cos q, sin q, -sin q, cos q, 0, 0)`, where q is the rotation angle.

for 90 degree rotation counterclockwise that would be:
`context.cm(0,1,-1,0,0,0)`

for 90 degree clockwise you'll need:
`context.cm(0,-1,1,0,0,0)`

**Comment by Ko-donghyun** [comment]
Wow.. It's really really really... amazing!!

Thank you! I'll try!!!!!

**Comment by thbl** [comment]
@galkahana do you have an example on rotating a page and afterward write text to it ? :)

**Comment by yortrosal** [comment]
How to do multiple page rotation?
