### ISSUE TITLE
Setting 'Content-Length' header?

### ISSUE THREAD

**Issue by marcinrog** [galkahana/HummusJS#60]
I'm just wondering, whether it is possible to set the correct 'Content-Length' header while using the HummusPDF library.

My case:
I need to 'merge' two pdfs into one pdf document:

`pdfWriter = hummus.createWriter(new hummus.PDFStreamForResponse(res));
pdfWriter.appendPDFPagesFromPDF(new hummus.PDFRStreamForFile(path1));
pdfWriter.appendPDFPagesFromPDF(new hummus.PDFRStreamForFile(path2));`

So, once again, it is possible with HummusPDF?

**Comment by galkahana** [comment]
Not sure that you need to set the content length. In my basic example here i dont:https://github.com/galkahana/HummusJS/blob/master/samples/PDFServer.js

I reckon you could try doing the pdf merging usibg similar code to tye sample anf seeing if it works. Would that be ok?

**Comment by marcinrog** [comment]
It works, I don't have any doubts:) but I need to fulfil the requirement, and set the 'Content-Length' header - the iOS app firstly does the HEAD request to our API (which serves the PDF files) to check if the device has enough memory to download file. That's why I would like to set the header with correct value.

**Comment by galkahana** [comment]
I see. In that case youll have to write the pdf first to another stream, get its length and only then write it to a response.
