### ISSUE TITLE
Add pages between pages

### ISSUE THREAD

**Issue by adityaanand4** [galkahana/HummusJS#61]
I am trying to add pdf pages between 2 pages, Is it possible to do so? Because I have not found anything like this in Hummus or Hummusrenderrer, If I set modifiedFrom value, It always add the object created to specified page.

**Comment by galkahana** [comment]
never tried this (maybe possible with changing order of pages after adding them). changing order is demonstrated here - r/blob/ff6aa2e0e0724524db14f413178c8bc2b636b2a5/PDFWriterTestPlayground/PageOrderModification.cpp

however the simpler approach is probably to just create a 3rd PDF and importing the pages that you want to in their respective order.

**Comment by adityaanand4** [comment]
sure,I'll try this approach.

**Comment by adityaanand4** [comment]
how can we do it with JS?

**Comment by galkahana** [comment]
the 2nd approach, simple one is using the embed functionality of hummus. read about it here:
https://github.com/galkahana/HummusJS/wiki/Embedding-pdf

**Comment by adityaanand4** [comment]
Yes it worked, Thanks. Is there any way to linearize that PDF?

**Comment by galkahana** [comment]
not with hummus. hummus doesn't create linearized pdfs.

**Comment by adityaanand4** [comment]
So how do you suggest I do it in JS?

**Comment by galkahana** [comment]
i don't know. maybe see if you can find some other libs that do.
i think that hummus maintains the linearized data if it modifies a pdf. so that's another option. [in this case the first path is what you want.]
how much of a big requirement is it that the pdf is linearized?

**Comment by adityaanand4** [comment]
Well It is quite significant as the pdf size is 18-20 MB and it takes a lot of time to load.
