### ISSUE TITLE
Question: How to generate pdf with password protection?

### ISSUE THREAD

**Issue by bjrmatos** [galkahana/HummusJS#63]

**Comment by galkahana** [comment]
No can do at this point, i'm afraid.
Hummus does not support either reading or writing of encrypted files.

**Comment by bjrmatos** [comment]
Do you plan to support that feature? Just asking because i think it will the first nodejs package to do that! :)

**Comment by galkahana** [comment]
@bjrmatos i'm thinking about it.
At first i thought that it's gonna be a big impossible deal, but i see some other Open source libs (C++) doing that...so i guess i can manage.

Tell you what though, i'm a little bit busy. building this PDF modification/creation service that i will probably launch sometime.
As it seems password encryption is something that will be a good feature for it, and since it will rely on the hummus library/node module it will be added.

So at this point let's discuss the feature requirement. In terms of API, what are we looking at? you just provide the pwd and request to encrypt (say in the PDFWriter constructor). other options that are fitting here?
Another, if you don't mind - how many PDFs do you plan to create. over what period etc.

**Comment by bjrmatos** [comment]
> you just provide the pwd and request to encrypt (say in the PDFWriter constructor).

yes, for pdf creation i think this is all the we need, for modification since `.createWriterToModify` uses the same options that pdf creation this will be covered too, for parsing/reading a pdf i think we'll need an option object in the API to be able to specify the password.



> Another, if you don't mind - how many PDFs do you plan to create. over what period etc.

my main use for HummusJS will be to modifiy an existing PDF to secure it with a password, i'm a collaborator in the [jsreport project](https://github.com/jsreport/jsreport), we generate PDF using [phantomjs](http://phantomjs.org/) and [electron](http://electron.atom.io/) so i'm looking for ways to protect the PDF files that we generate (something important in some enterprise scenarios with sensitive information).

another question: it is posible to concat two pdf files into one using hummusJS (basically joining multiple PDF's into one)? we had this feature [in mind some time ago](https://github.com/jsreport/jsreport/issues/122) but we stopped because of lack of libraries capable to do that

**Comment by galkahana** [comment]
understood. well, when i'll get to implement ecnryption/decription i'll notify.

As for merging pdfs, you can merge the pdf pages either into a new PDF or modify one and add others pages on it through PDF embedding features - https://github.com/galkahana/HummusJS/wiki/Embedding-pdf

the default merging process using `pdfWriter. appendPDFPagesFromPDF(inSourcePDFFilePath || inSourcePDFFileStream, [{PageRange}])` merges PDF pages content.
for more involved merging (for example, if you want to merge global objects like forms, or have a more advanced page merging that can merge items like annotations) you can use the [document copying context](https://github.com/galkahana/HummusJS/wiki/Embedding-pdf#advanced-pdf-embedding-with-documentcopyingcontext) which provided more granular copying.

**Comment by bjrmatos** [comment]
@galkahana thnk you! i'll dive into it!

**Comment by galkahana** [comment]
Password protection:
http://pdfhummus.com/post/147451287581/hummus-1058-and-pdf-writer-updates-encryption

**Comment by bjrmatos** [comment]
Sorry, I had lost the news in the ocean of notifications that i have from github 😄 

thnk you for this feature i will try it very soon! you rock!

**Comment by amitdevopsschool** [comment]
Anyone having node js project upload pdf file then add password , then download when open download pdf it should be ask password whatever i have to put in put then it would be open pdf file
