### ISSUE TITLE
Protection

### ISSUE THREAD

**Issue by jandersonmartins** [galkahana/HummusJS#64]
Can i disable copy content (CTRL + C) in pdf file?

**Comment by galkahana** [comment]
It should be possible with pdf, using pdf encryption feature. Sadly at this point hummus does not support creating/reading encrypted files

**Comment by galkahana** [comment]
Now it's possible:
http://pdfhummus.com/post/147451287581/hummus-1058-and-pdf-writer-updates-encryption
