### ISSUE TITLE
Different language support

### ISSUE THREAD

**Issue by oreporan** [galkahana/HummusJS#65]
Hey Gal - great work :)
I'm trying to modify a PDF and inject hebrew text, but its printing them backwards, do I just need to use a different ttf file or can this be set using an rtl/ltr option?

Toda

**Comment by galkahana** [comment]
Hi,
writeText doesn't handle RTL by itself. just places the characters according to the strings order of characthers.

What you can do about this is to reverse the text, if you know it's Hebrew, or use a more generic solution like what icu-bidi provides. this will do reversing where required.

See #56. my first response describes how to go about this. the rest is a discussion of how to add support for Arabic script writing.
