### ISSUE TITLE
Adding text with spacing on an existing PDF

### ISSUE THREAD

**Issue by ankitrshah89** [galkahana/HummusJS#66]
Hi Gal,

Firstly thank you for creating hummusJS.

I am trying to modify an existing PDF to add text with spacing to it. The feature that I need to use is the text showing operators, specifically Tj.

The hurdle that I am facing is that the examples that I could find,create new pages and then use the context from that page.

Now if My question is if it is possible to modify an existing page and utilize the Tj operator. Till now I have the following code snippet:

let hummus = require('hummus');

var pdfWriter = hummus.createWriterToModify('./samplePdfs/EmptyPages.pdf', {
  log: './logs/hummus.log',
  modifiedFilePath: './outputPdfs/sample1.pdf'
});

var pageModifier = new hummus.PDFPageModifier(pdfWriter,0);

pageModifier.startContext().getContext()
.BT()
.k(0,0,0,1)
.Tf(pdfWriter.getFontForFile('./fonts/OpenSans-Semibold-webfont.ttf'))
.Tm(14,0,0,14,65,600)
.Tj('Test Text')
.ET();

pageModifier.writePage();
pdfWriter.end();

Appreciate your help.
Thanks!

**Comment by galkahana** [comment]
Looks good. is the code not doing what you would want?

**Comment by ankitrshah89** [comment]
Hi Gal,

Thank you for the response.
I had actually missed out on adding endContext()
It works as expected now :)

Thanks!
