### ISSUE TITLE
String enconding

### ISSUE THREAD

**Issue by catacs** [galkahana/HummusJS#67]
I am using writeText method to fill pdf with some data, but I found that using non english characters result in a undesireble result.

I tried to write the word "España" and the result was "Espaæa".

Is there any way to specify the enconding?

Thanks

**Comment by galkahana** [comment]
Encoding is utf8. If you wabt to use something else, do so and convert to utf8 when providing to hummus

**Comment by galkahana** [comment]
sorry. this is the js thing.strings should be unicodes. reckon ñ is good enough as is.
i think you may have the string right. maybe the font doesnt have this glyph?

**Comment by catacs** [comment]
I am using this font http://www.1001fonts.com/raleway-font.html#character-map-regular so the glyph is not the problem

**Comment by galkahana** [comment]
then i have no idea. works for me.
wanna send me a script sample and a result pdf? maybe i can figure this out.

**Comment by catacs** [comment]
Than you, I have made a simple test writing with the font an empty pdf and it works. It seems to be the encoding in the original pdfs. That pdfs comes with 'latin1' encoding.

**Comment by catacs** [comment]
I have processed the text before writing it, removing diacritics and so on. In spite of not being the real solution, it solves my problem for now.
So, I think we can close this issue.

**Comment by galkahana** [comment]
Thanks man. This is something to look into, sometime.

**Comment by catacs** [comment]
Oh man, this issue was related to #70. So that is my real solution for diacritics.
