### ISSUE TITLE
Error while using custom streams

### ISSUE THREAD

**Issue by ankitrshah89** [galkahana/HummusJS#68]
Hi Gal,

I am trying to use very simple custom streams for reading and writing.

The code is below : 

[PDFReadStream.txt](https://github.com/galkahana/HummusJS/files/251008/PDFReadStream.txt)
[PDFWriteStream.txt](https://github.com/galkahana/HummusJS/files/251009/PDFWriteStream.txt)

The error that I get after I create a writer 
`var pdfWriter = hummus.createWriterToModify(inStream, outStream);`

is : 

Unable to modify PDF file, make sure that output file target is available and that it is not protected

Any help would be great.

Thanks,
Ankit

**Comment by galkahana** [comment]
Donnow. interfaces for both objects look ok.
maybe try plain functions instead of es6 classes?
