### ISSUE TITLE
Output Http Stream when modifying

### ISSUE THREAD

**Issue by jaspersorrio** [galkahana/HummusJS#69]
Hi all! 

Just want to check how do i write to an http stream with `var pdfWriter = hummus.createWriter(new hummus.PDFStreamForResponse(res));` when i am modifying a file?

Because the example for [modification](https://github.com/galkahana/HummusJS/blob/master/tests/ModifyExistingPageContent.js) shows the options being a file path.

````
var pdfWriter = hummus.createWriterToModify(__dirname + '/TestMaterials/BasicJPGImagesTest.PDF', {
  modifiedFilePath: __dirname + '/output/BasicJPGImagesTestPageModified.pdf'
});
````

**Comment by galkahana** [comment]
Yeah, a little bit confusing there.
Creating a writer for modification can happen in either of these ways:

````
var writer = hummus.createWriterToModify(inFilePath,[{inOptionsObject}])

OR

var writer = hummus.createWriterToModify(inSourceStream,inTargetStream,[{inOptionsObject}])
````

So you should take the 2nd option.
The first parameter is an input stream, the 2nd an output stream. For example, if you want to input from a file and output to the response object just go:
````
var pdfWriter = hummus.createWriterToModify(
                                 new hummus.PDFRStreamForFile(
                                                     __dirname + '/TestMaterials/BasicJPGImagesTest.PDF'), 
                                 new hummus.PDFStreamForResponse(res)
});
````

You can read about it [here](
https://github.com/galkahana/HummusJS/wiki/Modification#creating-a-writer-for-file-modification)

**Comment by jaspersorrio** [comment]
Wow fast reply! Thank you so much @galkahana! Yup how can i miss that!
