### ISSUE TITLE
Form field values not appearing in appended PDF pages

### ISSUE THREAD

**Issue by eliotharper** [galkahana/HummusJS#73]
We've created a simple app at:

	var hummus  = require('hummus')
	  , fs = require('fs')

	var pdfWriteStream = new hummus.PDFWStreamForFile('_!test.pdf')
	var pdfWriter = hummus.createWriter(pdfWriteStream )
	pdfWriter.appendPDFPagesFromPDF('routes1.pdf')
	pdfWriter.end()
	pdfWriteStream.close(function () {
	  console.log('[hummus] success generating pdf')
	})

I note that if my PDF file contains populated form fields [like this example](http://foersom.com/net/HowTo/data/OoPdfFormExample.pdf) then the form field values are not displayed on the appended pages.

**Comment by galkahana** [comment]
OMG your a hummus user :) happy times.

yeah sure...form is a catalog object. and for pages i only copy their content. so no widget annotations get copied and the form itself does not.
we can probably build a working example using the new pagewrite and catalog write events.

see here for the events:
https://github.com/galkahana/HummusJS/wiki/Extensibility#listening-on-events

see here for an example of copying annotations:
http://pdfhummus.com/post/142246893036/hummusjs-1052-events
similarly the catalog write event can be used for copying an AcroForm entry if it's there.

give it a try if you may...i'll look into it myself when i get some time. thanks for the PDF example.

Gal.

**Comment by eliotharper** [comment]
Hey @galkahana, yes we've been using hummus for a while. Thanks for the link to copy annotations, that's exactly what I needed.
