### ISSUE TITLE
Draw image using base64 representation of image

### ISSUE THREAD

**Issue by andrejkaurin** [galkahana/HummusJS#77]
Is there option to draw image using base64 representation of image?

"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAZAAAAEsCAYAAADtt+XCAAAgAElEQVR4nNS6Z1xVaZbvv/c+CVOZc6mYEMlJMZRizgljGRARs6AgOSMGQATBSM5ZyTkoOQkSzJWrp3t6etLt6Z7pmf/c++L7f3EOiBZW2dM9dz73xfdzztl7n3Oe/Txrrd9a69mCTC4gkwvIZAKSTECUBARRQBA+jii+46f ...."

**Comment by galkahana** [comment]
We'll, it makes decoding the 64 bit part and providing the decoded version to hummus. Make sure that the decoded images is supported image type. Png isnt.

**Comment by elgubenis** [comment]
i used the startContext().getContext().writeText() example of the createWriterToModify and replaced writeText with drawImage but i get an error, could you provide an example of modifying an existing pdf page with adding an image, instead of creating a new page with the image? 👍

**Comment by galkahana** [comment]
see #82. My last comment has a sample script. the required materials are provided earlier.
i think that you got it right. perhaps share the error that you got? or sample script/materials?

Gal.
