### ISSUE TITLE
How to get page dimensions 

### ISSUE THREAD

**Issue by andrejkaurin** [galkahana/HummusJS#80]
I want to position text on page center but cannot find documentation to get page dimensions so I can calculate.

**Comment by galkahana** [comment]
Hi,
you should use `parser.ParsePage(pageIndex)`, which will give you a page info object.
through which you can use its getMediaBox() which should give you the page rectangle out of which width/height can be computed.
see here https://github.com/galkahana/HummusJS/wiki/Parsing#page-info-objects
