### ISSUE TITLE
Adding images in header and footer area

### ISSUE THREAD

**Issue by thomasuh** [galkahana/HummusJS#82]
Im am completely new to HummusJS and now searching for several ours for something helping me with my Problem.

I have lots of pdf files which should get some kind of images in the upper left corner. Those source pdfs all habe a big margin to the top of the documents. I followed the Modification example and found out that 

`ctx.drawImage(0,0, "test.jpg")` places the image at the top left of the content area. Selecting a negative value like  `ctx.drawImage(0,-50, "test.jpg")`the result is a cutted image. Same result when using XObjects as well. 

Is there a workaround avoiding copying all contents into a new pdf file with smaller margins or changing the margins without moving the contents of the existing pages?

Thanks a lot for your answer...

**Comment by galkahana** [comment]
you can change the margins yes. but it might be that changing the margins will move all the content to the respective position without the margins. do this by modifying the page media box.
[this](https://github.com/galkahana/HummusJS/blob/master/tests/ModifyingExistingFileContent.js#L86) script shows how to do that. you can get info on the current boxes of the page by parsing page info [see here](https://github.com/galkahana/HummusJS/wiki/Parsing#page-info-objects).

however it does sound weird that the page is cropped and that there's nothing that you can place outside of its margins...unless there's a clip in play.
hmfff.

any chance of getting this PDF with a sample script of what you already tried. i might be able to look into it and provide a more precise suggestion.

Gal.

**Comment by thomasuh** [comment]
I really would be happy about a suggestion. Here is my (simplified-coffescript) code:

```
path = require("path")
hummus = require("hummus")
source = path.resolve("test.pdf")

#test draw direkt to pdf
targetFileWithHeaders = "#{new Date()}_out_drawimage.pdf"
writer = hummus.createWriterToModify(source, {modifiedFilePath:targetFileWithHeaders})
pageModifier = new hummus.PDFPageModifier(writer,0)
ctx = pageModifier.startContext().getContext()
ctx.drawImage(0,-50, "test.jpg")
pageModifier.endContext().writePage()
writer.end()
console.log "#{targetFileWithHeaders} done"


#test draw xObject
targetFileWithHeaders = "#{new Date()}_out_qobject.pdf"
writer = hummus.createWriterToModify(source, {modifiedFilePath:targetFileWithHeaders})
imageXObject = writer.createImageXObjectFromJPG('test.jpg');
pageModifier = new hummus.PDFPageModifier(writer,0)
ctx = pageModifier.startContext().getContext()
ctx.q().cm(500,0,0,400,0,-100).doXObject(imageXObject).Q();
pageModifier.endContext().writePage()
writer.end()
console.log "#{targetFileWithHeaders} done"
```

i attached source coffee and js as well as pdf and jpg file...

[pdfjpgandsourcecode.zip](https://github.com/galkahana/HummusJS/files/349337/pdfjpgandsourcecode.zip)

**Comment by galkahana** [comment]
Hi,
Looking at the content stream I see that it does two things that interfere with simple modification of the page:
1. it applies a global matrix which flips the page vertically, turning from the default Cartesian coordinate system to a computer scree one
2. it applies a clip around the page content

One suggestion that i could give you is to use the modifier content context option, create a form out of the first page content and replace the content stream with a new one that places that form. This way the content will be encapsulated and your modifications won't get the clip and matrix. This is quite involved and complex.

however there's a simpler approach and it is to simply change the page modifier (hummus.PDFPageModifier) to allow encapsulation of the original page content stream. This will remove the effects of the matrix and clip when the modification comes into play, and you code can assume that its a plain cartesian matrix with no clip and so place the image wherever you want on the page (which is (0,pageHeight-imageHeight), both numbers you can get from hummus, if you need to know how let me know).

In the follow hour i will write the relevant code, submit a new version of hummus and let you know of more details instructions.

Gal.

**Comment by galkahana** [comment]
Good. so with hummus 55, you should be able to do the following:

````
var ctx, hummus, imageXObject, pageModifier, source, targetFileWithHeaders, writer;

hummus = require('hummus');
var path = require('path');

source = path.resolve("test.pdf");

targetFileWithHeaders = "out_drawimage.pdf";

writer = hummus.createWriterToModify(source, {
  modifiedFilePath: targetFileWithHeaders
});


pageModifier = new hummus.PDFPageModifier(writer, 0, true);

var pageTop = writer.getModifiedFileParser().parsePage(0).getMediaBox()[3];
var imageHeight = writer.getImageDimensions("test.jpg").height;

pageModifier.startContext().getContext().drawImage(0, pageTop-imageHeight, "test.jpg");

pageModifier.endContext().writePage();

writer.end();
````

note this part in particular:
`pageModifier = new hummus.PDFPageModifier(writer, 0, true);`

the new last parameter ensures that the existing content is well encapsulated meaning that your new code is not affected by any global definitions it may have, like a clip or a matrix.
