### ISSUE TITLE
PDF is not modified and no errors displayed

### ISSUE THREAD

**Issue by cortopy** [galkahana/HummusJS#85]
I'm unable to edit or modify the following [pdf file](http://s3-eu-west-1.amazonaws.com/hmctsformfinder/n1-eng.pdf)

If I try to add a page, I get exactly the same pdf file back

```
var pdfWriter = hummus.createWriterToModify('/home/juan/Downloads/n1-eng.pdf', {
					modifiedFilePath: '/home/juan/Downloads/n1-eng2.pdf'
				});

				var page = pdfWriter.createPage(0,0,595,842);
				pdfWriter.startPageContentContext(page)
					.BT()
					.k(0,0,0,1)
					.Tf(pdfWriter.getFontForFile('/home/juan/.fonts/Exo-SemiBoldItalic.otf',0),1)
					.Tm(30,0,0,30,78.4252,662.8997)
					.Tj('about')
					.ET();

				pdfWriter.writePage(page);
pdfWriter.end();
```

Likewise, if I try to add text, I get the same file too

```
var pdfWriter = hummus.createWriterToModify('/home/juan/Downloads/n1-eng.pdf', {
  modifiedFilePath: '/home/juan/Downloads/BasicJPGImagesTestPageModified.pdf'
});

var pageModifier = new hummus.PDFPageModifier(pdfWriter, 1);
pageModifier.startContext().getContext().writeText(
  'Test Text',
  75, 50, {
    font: pdfWriter.getFontForFile('/home/juan/.fonts/Exo-SemiBoldItalic.otf'),
    size: 14,
    colorspace: 'gray',
    color: 0x00
  }
);

pageModifier.endContext().writePage();
pdfWriter.end();
```

Is this because the pdf file has a form in it? I've been reading the wiki but can't find info about what the requirements are for pdf files (version, etc.)

This is puzzling to me as I'm just using the examples from the unit tests

**Comment by galkahana** [comment]
Try getting up a log. Youll be able to see the errors there

**Comment by cortopy** [comment]
How would I get a log? It just looks like node thinks the script run OK.

**Comment by galkahana** [comment]
in that same object that has "modifiedFilePath" add a key named "log" which value can be used to provide a file path to write a log into. for debugging mainly.

+ do the unit tests work?

**Comment by cortopy** [comment]
Yes they do. And I've tried with different files and it works with them too. However, I was asking because there seems to be an issue with this particular file.

Would it be possible to know what the requirements are for hummus to process a pdf file? For example: pdf version, whether it can contain forms or has to be flatten, etc.

**Comment by galkahana** [comment]
it can anything but encrypted files

**Comment by galkahana** [comment]
[Archive.zip](https://github.com/galkahana/HummusJS/files/359486/Archive.zip)

downloaded the PDF to my mac. tried your first script with arial, worked very well for me.
attaching all relevant materials

**Comment by galkahana** [comment]
forgot the result:
[n1-eng2.pdf](https://github.com/galkahana/HummusJS/files/359491/n1-eng2.pdf)

**Comment by cortopy** [comment]
I just opened n1-eng2.pdf and it still has two pages. I'm not sure if I'm missing something.
This is the screenshot:

![screenshot from 2016-07-12 14-57-28](https://cloud.githubusercontent.com/assets/8725825/16769541/124b8330-4841-11e6-8226-128c3d299209.png)

**Comment by galkahana** [comment]
i have no idea. im seeing 3 pages.

**Comment by cortopy** [comment]
Now, this is getting even weirder. On my linux computer, the file has two pages (tried with Okular and Document Viewer). On my windows machine same file has three pages!

I have no idea why this can be either

**Comment by elgubenis** [comment]
hi, i have similar issues on linux, just that the unit tests did not pass in my case. how did you run them @cortopy just using "npm test"?

**Comment by cortopy** [comment]
@elgubenis I should have been more specific. I didn't run the tests with mocha, I just used the same code in my sandbox. Hummus is working for me for some files, but the one I linked for this issue is the problematic one. 

I suspect tests would run OK anyway. Humus is doing its thing and no errors are being generated. It's just the modifications are visible in Mac/Win but not Linux.

**Comment by galkahana** [comment]
How about your second script, does it create a pdf that behaves the same (meaning - no new visuals on linux viewers, yes on mac/windows viewers)? can you check?

**Comment by cortopy** [comment]
I was so puzzled by this that I have tried both scripts and both have same results. I'm starting to be more convinced that the issue is with the forms in the file.

Whether I add text or a page, the modifications can only be seen on Windows (I have no mac). In Linux, the files look exactly the same. However, I can still see something has been added as they are about 7k bigger. Forms can be used just the same way as the original file.

It would seem that this is a Linux issue. However, on Windows, when I open the file with added text I get a warning saying that the use of extended features is no longer available because the file has been modified from the original. The added text is there. However, the form functionality is gone.

It's as if Linux chooses to keep form functionality and ignore modifications, whereas Windows (Adobe Reader DC) chooses to remove forms for the sake of showing modifications

**Comment by galkahana** [comment]
ok. the first case rewrites the catalog which removes all keys including the form.
which is why it makes sense that you will lose the form functionailty. a bug if you will.
the 2nd case, however, does not alter the catalog and form functionality remains.
are you positive that the 2nd case where you use only the pdf page modifier, DOES NOT show the changes?

**Comment by galkahana** [comment]
ah ok. i see now.
look. this pdf has a signature which means you cannot modify it. i mean, modifications should be ignored or some functionality removed, as is what you experience.
you can tell this because it has a "Perms" entry in its Catalog object.

So, with this PDF (not so much the form, rather the "Perms" part), there's no win. you cant modify it with the library. somehow the signature need to be removed and reapplied, and this current version doesn't handle this.

It is still worth while to fix the fact that a  catalog recreation in case of modified file kills the existing catalog keys, but its not gonna solve your problems anyways.
sorry.

**Comment by elgubenis** [comment]
one thing you could to @cortopy is turn the pdf into html make your changes and turn it into a pdf again.

**Comment by galkahana** [comment]
k. decided to fix the catalog thing regardless. it was a silly bug. version 1.0.58 should take care of this.
anyways, still doesnt help our problem here.
any chance of you getting the input PDF without it being signed?

Gal.

**Comment by cortopy** [comment]
Thanks both @elgubenis and @galkahana 
This has been really helpful. Here in the UK, the government tends to issue a lot of official forms in PDFs, which for some reason they call "software". I've even submitted full company financial accounts using one of those.

Luckily, I've noticed this particular form has a "Print" button. It doesn't work on Linux as pdf support will never be good due to the proprietary issues that Adobe keeps pushing in. However, after printing an empty copy of the pdf in Windows, I get a good plain pdf which now I can modify without unexpected results

Only thing worth mentioning is that perhaps if a pdf has features like this one, it would be good that there's some logging to console warning developer that something may not work as expected?

**Comment by galkahana** [comment]
yeah! defo. 
It's just that i wasn't aware of this feature at all. i'll put a note to sometimes do this.

**Comment by cortopy** [comment]
Thanks!!!
