### ISSUE TITLE
get last page with startContext?

### ISSUE THREAD

**Issue by elgubenis** [galkahana/HummusJS#87]
is there a way to get the last page of a pdf to modify?

**Comment by elgubenis** [comment]
it seems like with new hummus.PDFPageModifier(writer, 1); i get to page two, how could i find out the number of pages?

**Comment by galkahana** [comment]
get the parser of a modified pdf:
https://github.com/galkahana/HummusJS/wiki/Modification#pdfwriter-a-la-modification

get info from parser:
https://github.com/galkahana/HummusJS/wiki/Parsing#creating-a-parser-object-and-high-level-functions
