### ISSUE TITLE
Prebuilt Binaries

### ISSUE THREAD

**Issue by unimaginativeGitHub** [galkahana/HummusJS#89]
Hey Galkahana,

Thanks again for building such an awesome pdf tool.  Would it be possible to create some prebuilt binaries for later versions of node than v4.x.x?  Maybe versions for 6.2.2?

I've been having trouble with (I think) my build dependencies when I try to install HummusJS on an Amazon EC2 instance running node 6.2.2, it doesn't want to build the binary.  While install on a Mac with node 6.2.2, build is no problem.

Any advise is welcome!

Thanks again for all you've made!

- Bradley Cooper

**Comment by galkahana** [comment]
Sure,
Go get  your binaries. Added for 5.X.X and 6.X.X.

Good luck,
Gal.

**Comment by unimaginativeGitHub** [comment]
Awesome!

Thanks Gal!

**Comment by elgubenis** [comment]
how can i download the prebuilt binaries?

**Comment by elgubenis** [comment]
https://hummus.s3-us-west-2.amazonaws.com/

**Comment by brianreavis** [comment]
@elgubenis They are automatically downloaded and used when you `npm install` hummus (assuming you have a matching platform / matching version of node)
