### ISSUE TITLE
added image appears rotated when skia 

### ISSUE THREAD

**Issue by elgubenis** [galkahana/HummusJS#90]
i got a pdf with the following properties:
https://www.dropbox.com/s/m0giip965100fpk/Screenshot%202016-08-01%2018.03.42.png?dl=0

when i add an image, the image appears rotated 180 deg. every other pdf i have the attached image appears alright.

the file is this one: 
https://www.dropbox.com/s/7m2egj8gimfbu3v/attachments%20like%20image%20appear%20rotated.pdf?dl=0

the code i use to attach the image is the following:
```js
  const writer = hummus.createWriterToModify('/var/tmp/pdf.pdf', {
    modifiedFilePath: '/var/tmp/pdf_2.pdf',
  });

  const pdfReader = hummus.createReader('/var/tmp/pdf.pdf');
  const pageModifier = new hummus.PDFPageModifier(writer, pdfReader.getPagesCount() - 1);
  const ctx = pageModifier.startContext().getContext();
  ctx.drawImage(left, bottom, '/var/tmp/signature.jpg', {
    transformation: {
      width: 200,
      proportional: true,
    },
  });
  pageModifier.endContext().writePage();
  writer.end();
```

only on the SKIA pdf the image is rotated 180 deg. any idea?

**Comment by elgubenis** [comment]
also i found out that only the pdf 1.5 version has this issue, all the other files were the image is not rotated are 1.3 or 1.4

**Comment by galkahana** [comment]
The page must have a sort of global rotation.
To avoid being affected by graphic settings made by the existing content add 'true'  as a 3rd parameter to PDFPageModifier constructor

**Comment by elgubenis** [comment]
that did the trick, thanks!
