### ISSUE TITLE
Chinese characters

### ISSUE THREAD

**Issue by jaspersorrio** [galkahana/HummusJS#92]
Hi @galkahana, everything has been working out smoothly. However, how do i add Chinese Characters to the pdf? 

I keep getting this error and i am using the font, [PingFang.ttc](https://gist.github.com/bitinn/42c95ed95aa3dcf155e2)

Input 衫仲 -> Output ㄹㄴ〵㙣
And the color of the font is always white in color.

**Comment by galkahana** [comment]
Could you send me a sample script? i want to see how you input the text. not sure why its not working.

Gal.

**Comment by galkahana** [comment]
@jaspersorrio i fixed a bug directly related to this issue now. check version 1.0.60.
checked these chars with pingfang, and they seem fine now
Gal.

**Comment by jaspersorrio** [comment]
Hey @galkahana sorry I replied so late! I couldn't find the time to test this out. But thank you for your prompt replies as always!

I will post my results here soon.

**Comment by jaspersorrio** [comment]
<img width="66" alt="screen shot 2016-09-14 at 6 27 56 am" src="https://cloud.githubusercontent.com/assets/10573718/18493698/75b62648-7a44-11e6-84e0-a7eb6bbe85e3.png">
As expected this is the output.

Thanks @galkahana!
