### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by alexandremaeda** [galkahana/HummusJS#93]
Error when trying to install on windows 10

`> hummus@1.0.58 install d:\Projetos\bsapi\node_modules\hummus`
`> node-pre-gyp install --fallback-to-build`
`node-pre-gyp ERR! Tried to download: https://hummus.s3-us-west-2.amazonaws.com/hummus/v1.0.58/node-v46-win32-x64.tar.gz`
`node-pre-gyp ERR! Pre-built binaries not found for hummus@1.0.58 and node@4.4.7 (node-v46 ABI) (falling back to source compile with node-gyp)`

**Comment by brianreavis** [comment]
This error is expected – automatic pre-built binaries are not set up for Windows. Getting those available requires configuring [AppVeyor](https://www.appveyor.com/), which is a decent-sized endeavor.

The install still continues though, right?

**Comment by alexandremaeda** [comment]
Does not continue.

``
``
``
``
``
``

**Comment by galkahana** [comment]
Can't recreate on my pc. Anything more specific as to what exactly fails? Maybe you don't have a build env? We need more verbose error message

**Comment by alexandremaeda** [comment]
@galkahana 
I do not know what else I can show you.
I just can not install this depedência. He accuses an error and rolls back the installation.

node version: 4.4.7
npm version: 3.3.9

[npm-debug.log](https://gist.github.com/alexandremaeda/cc85adab781fcab371e547b6911a9fdb)

**Comment by galkahana** [comment]
do you have a compiler installed on this machine? for example visual studio, gcc?

**Comment by alexandremaeda** [comment]
Yes. Visual Studio.

**Comment by galkahana** [comment]
So i dont know whats the problem

**Comment by brianreavis** [comment]
@galkahana Perhaps we can bump node-pre-gyp to the latest version to see if that has an effect? Or at least to see if it'll give an error when it fails...

**Comment by alexandremaeda** [comment]
As feedback, I could finally use.
The problem was with node-gyp.
After a few adjustments, it worked.

**Comment by galkahana** [comment]
Very good.

**Comment by brianreavis** [comment]
@alexandremaeda Out of curiousity, what adjustments were needed? Others on Windows seem to be having the same problem

**Comment by alexandremaeda** [comment]
Basically I was correcting the console errors.
I had not installed on my machine the version of Python 2.7.
After that I had several problems with Visual C ++ Build Tools.

I followed the installation's own lib [node-gyp](https://github.com/nodejs/node-gyp).
