### ISSUE TITLE
pageModifier.writePage(); seems to time out

### ISSUE THREAD

**Issue by tsestrich** [galkahana/HummusJS#94]
Hi,

First of all - Hummus has been awesome and it's been a huge help in the project I've been working on!

I'm running into some issues, though, with a few PDFs when trying to do simple page modifications. In this code example, all I'm trying to do is to retrieve a signature image that is stored in another PDF and then superimpose it on top of an "original" PDF file. This works great for a large number of PDFs! However, on some files it will simply "hang" when trying to execute "pageModifier.writePage()". Despite turning on logging, it doesn't output any log output, and it doesn't throw an exception. All that happens is that my CPU slowly starts to max out, and my code never continues. I found an email of yours in another issue and I will send you a sample PDF file.

To be clear, I am able to overlay the signature image perfectly fine on other documents, so I assume there is no issue with that file. It appears to be something to do with how writePage is handling certain PDFs.

       var targetFileWithHeaders = "/tmp/" + docUniqueId + "-signed.pdf";
        
        var writer = hummus.createWriterToModify(tempPDFFileNameIn, {
          modifiedFilePath: targetFileWithHeaders,
          log: "/tmp/log-" + docUniqueId + ".txt"
        });
        
        var pageModifier = new hummus.PDFPageModifier(writer, 0);
        
        var pageContext = pageModifier.startContext().getContext();
        
        pageContext.drawImage(0,0,signatureImageLocation);
        
		pageModifier.endContext();
		pageModifier.writePage();
		writer.end();

**Comment by galkahana** [comment]
Hi man,
getting back to you.

pageModifier had a silly bug when a PDF with annotations that are defined in  certain way comes its way.
i fixed the bug and the file seems to modify properly now. check hummusjs 1.0.59.
thanks for the sample file you sent me!
Gal.

**Comment by tsestrich** [comment]
Awesome! You're the best! That fixed the problem for not only that, but a few other PDFs I had that weren't working. Thanks for the fast work!

**Comment by galkahana** [comment]
Lovely :)
