### ISSUE TITLE
How to use utf8 character

### ISSUE THREAD

**Issue by saknarak** [galkahana/HummusJS#95]
I want to convert utf8 character to work with writeText method
How to convert that?
How to use this method TranslateStringToGlyphs()

```
var pdfWriter = hummus.createWriter(new hummus.PDFStreamForResponse(res));
var page = pdfWriter.createPage(0,0,595,842);
pdfWriter.startPageContentContext(page).writeText('Hello สวัสดี ', 0, 400, { // Thai
  font:pdfWriter.getFontForFile('./fonts/leelawad.ttf'), // a font that include Thai
  size:50,
  colorspace:'gray',
  color:0x00
});
```

No text was printed, no "Hello", no "สวัสดี", all are empty.

**Comment by galkahana** [comment]
i corrected a bug directly tied to this problem now.
checked leelawad with those chars and it looks good now.
check version 1.0.60.

Gal.

**Comment by saknarak** [comment]
It's work. Thank you very much for your effort :+1: .  I'm very happy :smile:
