### ISSUE TITLE
Unable to add image to the bottom of every page of existing pdf

### ISSUE THREAD

**Issue by vvsanil** [galkahana/HummusJS#98]
Hi Gal,

I am new to  Hummus. I want to add some logo in each page of existing pdf.  But while adding image it was overlap with the content of the page with this code.

```
 var pdfWriter = hummus.createWriterToModify(sourcePath, {modifiedFilePath:resultPath});
 var pageModifier = new hummus.PDFPageModifier(pdfWriter,0,true);
 var pageTop = pdfWriter.getModifiedFileParser().parsePage(0).getMediaBox()[3];
 var imageHeight = pdfWriter.getImageDimensions("./logo.jpg").height;
 pageModifier.startContext().getContext().drawImage(0, pageTop-imageHeight, "./logo.jpg");

```

How can I add image to bottom of each page without overlapping with existing content.  

One more doubt. Is there any way to loop all pages of pdf  other than this logic. I am looping each page and combing all in to one.

```
pdfReader = hummus.createReader('main.pdf')
for(var i=0;i<pdfReader.getPagesCount();++i){
   pdfWriter = hummus.createWriter('output' + i + '.pdf')
   pdfWriter.createPDFCopyingContext(pdfReader).appendPDFPageFromPDF(i);
   pdfWriter.end();
}
```

Sharing some example code will be helpful for me.

Thanks

**Comment by galkahana** [comment]
First. hummus coordinate system, like PDFs,  is a cartesian one. This means that coordinates should be given according to the distance from the bottom left corner. If you want an image to be placed at the bottom left of the page, than `.drawImage(0, 0, "./logo.jpg");` is what you want.

As for the second questions, the code that you provided creates a separate PDF for each page of the original PDF. Sharing the parser between them is a clever way of optimizing the creation of the copying context.
If you are looking to append pages of one pdf to another one pdf, you would use the same pdfWriter. and there's a shortcut to that - `pdfWriter. appendPDFPagesFromPDF`. you can read about it here - https://github.com/galkahana/HummusJS/wiki/Embedding-pdf#basic-page-appending

I hope this helps. If not, perhaps explain again what you are trying to accomplish.
Gal.

**Comment by vvsanil** [comment]
Hi Gal,

Thanks for reply. The problem is the content of PDF is overlapping with the image. The PDF page has content of entire page. I have to add my company logo in the bottom which leads to overlapping. So I have to reduce the original content to get place for my company logo in the bottom without extending the A4 dimensions.

I have to do that. Please help me for that. My PDF  contains multiple pages. I have to add the logo in all pages as I mentioned the above.

Please share some code snippet.

**Comment by galkahana** [comment]
ok. the best option here would be to create a new pdf out of the old one. For each page at the original document. than create a form from the old PDF page, and place it in the new page at 0,imageHeight. its size should be reduced proportionally to allow height-imageHeight. this can be done by placing a transformation matrix prior to its placement.
Then place the logo.

I can provide a snippet later, when i have more time.
i'll provide some pointers now:

use this to create a form from the original page:
`createFormXObjectFromPDFPage(inSourcePageIndex,inFormBox || inPageBoxEnum)`
instead of
`appendPDFPageFromPDF`
in the sample you provided.

the first sample here should show you how to place the form on a new page:
https://github.com/galkahana/HummusJS/wiki/Reusable-forms
(the .cm command is the one for placing the size reducing matrix. use 
[newHeight/oldHeight,0,0,newHeight/oldHeight,0,imageHeight]
where newHeight = oldHeight - imageHeight
)

if you need the original page dimensions use the copying context parser and get the original page data:
https://github.com/galkahana/HummusJS/wiki/Parsing#page-info-objects

and you already know how to place an image.

Regards,
Gal.

**Comment by vvsanil** [comment]
Thanks Gal,  I will explore and try.  Thanks for your support.

**Comment by vvsanil** [comment]
Hi Gal

Working on the above problem :) . There is an issue while copying content of PDF.

I am unable to delete the PDF once it is opened.

```
      var pdfWriter = hummus.createWriter('./sample.pdf');
      var cpyCxt = pdfWriter.createPDFCopyingContext(path);
      var page = pdfWriter.createPage(0,0,595,842);
      var pageContent = pdfWriter.startPageContentContext(page);   
      pdfWriter.writePage(page);
      pdfWriter.end();

     fs.remove(path,function(err){
          if(err){
         }
    });
```
It is throwing the error  "**resource busy or locked, unlink**".  Do I need to end createPDFCopyingContext stream manually ?  pdfWriter.end() is not closing the PDF in server side.

Thanks,
Anil.

**Comment by galkahana** [comment]
We'll if my memory serves me well, pdfwrite take care of closing only the file it is writing to. If you want the copied file to be close you should scope the copying content so it get destructed. This will probably allow you a delete

**Comment by vvsanil** [comment]
Gal, I did not understand what it mean by **scope the copying content. **  The source file will be in locked state and will not accessible by other functions. Can you please provide some more information about how can I delete the source file?

Thanks
Anil

**Comment by vvsanil** [comment]
Gal, I did not understand what it mean by scope the copying content. The source file will be in locked state and will not accessible by other functions. Can you please provide some more information about how can I delete the source file?

Thanks
Anil

**Comment by galkahana** [comment]
in scoping  i mean scoping the variable.
cpyCxt holds a reference to the copying context. i believe this keeps it in memory, and only its destructor will release the file. 
if you want to use the file take care of scoping cpyCxt.
like, put this in a function and do the remove after its execution. something like that.

Gal.

**Comment by vvsanil** [comment]
Completed my task. Thank you so much Gal.

**Comment by vvsanil** [comment]
Gal, I wrote some code to add logo in each  pdf  page. 

```
    var pdfWriter = hummus.createWriter(dest);
    var pdfReader = hummus.createReader(src);
    var cpyCxt = pdfWriter.createPDFCopyingContext(pdfReader);
    for (var i=0; i < pdfReader.getPagesCount(); ++i) {
           var formObjectId  =  cpyCxt.createFormXObjectFromPDFPage(i, hummus.ePDFPageBoxMediaBox);

            /* Some logic to add image */
     }

```
It is working for some PDF and for some PDF's,  getting the following error.
```
       var formObjectId  =  cpyCxt.createFormXObjectFromPDFPage(i, hummus.ePDFPageBoxMediaBox);
      
       TypeError: Unable to create form xobject from PDF page, parhaps the page index does not fit the total pages count
```

I did not find  any clue.  Please correct me if any thing wrong. If I display pagesCount  it is showing the exact number of pages.

Thanks,
Anil.

**Comment by galkahana** [comment]
maybe there's some other issue.
it's probably tied up to the pdf itself.
there might be a bug in createFormXObjectFromPDFPage, maybe the PDF is unsupported. 
wanna debug this?

**Comment by vvsanil** [comment]
Thanks Gal, I tried the same PDF with PHP library and it is working. Is there anyway to debug PDF?

  All PDFs from particular vendor are failing in hummus and same PDFs are working in FPDI PHP library. I tested other functions of adding text etc to that PDF in hummus,  Text is adding in blank pages. I thought hummus is unable to get It's content.  


I have to implement solution for adding logo. Without reading the context, Is there any other way to implement?

I think we have to look for solution to copy PDF page as image and place it on new PDF along with logo in the bottom.

I am not aware of how to handle this.


Thanks for spending your time.


Thanks,
Anil

**Comment by galkahana** [comment]
well, someone has to debug this. to figure out why hummus fails to read this pdf.
i was suggesting you would do it.
if you want me to look into it, attach a pdf that doesn't work, wait till i have time and will to debug this, and i will respond then.

**Comment by vvsanil** [comment]
Gal, can you suggest some debugging tips?

**Comment by galkahana** [comment]
well, i'll tell you what i'd do.
hummus is based on a C++ library, https://github.com/galkahana/PDF-Writer.
it's easier to debug the C++ code directly than to try to debug it via node.
So i'd write a matching C++ program, and either user breakpoints or prints to see where exactly does hummus get into the condition that leads it to err, in the implementation of createFormXObjectFromPDFPage. should be easy to figure out whether there's a solution, and what is it, from there.

**Comment by vvsanil** [comment]
Gal, can you share your email?  My email is "vvsanilkumar@gmail.com". I will share that PDF with you. Because it contains some information which should not be public.

**Comment by galkahana** [comment]
now this becomes interesting ;)
gal@pdfhummus.com should work :)

**Comment by jhonnynho** [comment]
Hi vvsanil

How did you get this to insert images in the footer?

**Comment by vvsanil** [comment]
Hi jhonnynho,

This code will add footer image in the bottom of every existing page.

```
function addFooter(src,dest){
    var pdfWriter = hummus.createWriter(dest,{version:hummus.ePDFVersion13});
    var pdfReader = hummus.createReader(src);
    var cpyCxt = pdfWriter.createPDFCopyingContext(pdfReader);
    var imageXObject = pdfWriter.createImageXObjectFromJPG('./logo.jpg'); // Footer logo or image location
    for (var i=0; i < pdfReader.getPagesCount(); ++i) {
        var formObjectId  =  cpyCxt.createFormXObjectFromPDFPage(i, hummus.ePDFPageBoxMediaBox);
        var pageInfo =  pdfReader.parsePage(i);
        var dimensions = pageInfo.getMediaBox();
        var oldWidth = 595;
        var oldHeight = 842;
        if(dimensions && dimensions[2]){
            oldWidth = dimensions[2];
        }
        if(dimensions && dimensions[3]){
            oldHeight = dimensions[3];
        }
        var imageHeight = 20;  // Height of the footer image
        var newHeight = oldHeight-imageHeight;
        var page = pdfWriter.createPage(0,0,595,842);
        var pageContent = pdfWriter.startPageContentContext(page);
        pageContent.q()
            .cm(newHeight/oldHeight,0,0,newHeight/oldHeight,5,imageHeight)
            .doXObject(page.getResourcesDictionary().addFormXObjectMapping(formObjectId))
            .Q();
        pageContent.q()
            .cm(130,0,0,13,225,4) //width, rotation angel ,rotation angel, height, left, bottom .   Placement of the footer logo.
            .doXObject(imageXObject)
            .Q();
        pdfWriter.writePage(page);
    }
    pdfWriter.end();
}
```
 Happy to help. Let me know if any issues :)

**Comment by jhonnynho** [comment]
Hi, this code works for me but if I use the same PDF to Write and Read, this functions add the same pages of a PDF after the last page with images! How I can add images in the same PDF without copying the pages?
